### ISSUE TITLE
Build delve failed

### ISSUE THREAD

**Issue by heretic13** [derekparker/delve#569] opened 2016-06-09 07:48 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
ede880134c0997ee18355cc20d85a8ca96512356 (actual for 2016.06.09)

2. What version of Go are you using? (`go version`)?
go version go1.6.2 windows/386

3. What operating system and processor architecture are you using?
Windows 8.1 Professional x64. Intel Core i7-4770

4. What did you do?
go get github.com/derekparker/delve/cmd/dlv
(as it is written in docs)

5. What did you expect to see?
nothing (successfull install)

6. What did you see instead?
# github.com/derekparker/delve/proc
delve\proc\disasm.go:9: undefined: ArchInst

**Comment by joegrasse** [comment] 2016-06-09 12:24
32bit isn't suppored.

**Comment by aarzilli** [comment] 2016-06-30 11:13
Duplicate of #20

**Closed by aarzilli** 2016-06-30 11:13 UTC
