### ISSUE TITLE
Type switch variable

### ISSUE THREAD

**Issue by lloiser** [derekparker/delve#673] opened 2016-11-18 11:19 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

I'm using a prebuilt version from https://bintray.com/jetbrains/golang/delve/ - version 0.11.309 (updated Nov 02, 2016)

```
Delve Debugger
Version: 0.11.0-alpha
Build: 
```

2. What version of Go are you using? (`go version`)?

```
go version go1.7.3 darwin/amd64
```

3. What operating system and processor architecture are you using?

```
$ sw_vers
  ProductName:	Mac OS X
  ProductVersion:	10.11.6
  BuildVersion:	15G1108
$ uname -mp
  x86_64 i386
```

4. What did you do?

Following test code:

```go
package type_test

import "fmt"
import "testing"

func TestMe(t *testing.T) {
	run("the answer")
	run(42)
}

func run(v interface{}) {
	switch av := v.(type) {
	case string:
		fmt.Printf(">> string %q\n", av)
	case int:
		fmt.Printf(">> int %d\n", av)
	}
}
```

```
$ dlv test

# set breakpoint at line `switch av := v.(type) {`
$ b type_test.go:12
$ c
# stop at above breakpoint

$ locals
av = 0
av = ""
$ n
$ n
# stop at `fmt.Printf(">> string %q\n", av)`

$ locals
av = 0
av = "the answer"
```

5. What did you expect to see?

Either only the string `av` variable, or the "unused" variable (`av = 0`) should be marked as "unused" or so. This would help both the dlv cli and editor plugins to display the correct value.

6. What did you see instead?

look at 4.

**Comment by aarzilli** [comment] 2016-11-18 12:12
Duplicate of #106, golang/go#12899 and golang/go#6913. See also: https://go-review.googlesource.com/#/c/29591/

**Closed by aarzilli** 2016-11-18 12:12 UTC
