### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by JamesYuan** [derekparker/delve#675] opened 2016-11-24 08:54 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
elve Debugger
Version: 0.11.0-alpha
Build: a1f31a83b4a295322b8b59327338b7d3311e6766

2. What version of Go are you using? (`go version`)?
go version go1.7.3 darwin/amd64

3. What operating system and processor architecture are you using?
macOS Sierra, Version 10.12.1 (16B2555),
Procesor 2.2 GHz Intel Core i7

4. What did you do?
Debug a Go main program.

5. What did you expect to see?
Debug the Go program step by step.

6. What did you see instead?

API server listening at: 127.0.0.1:49274
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x41ecdaa]

goroutine 38 [running]:
panic(0x44a8780, 0xc4200140d0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/derekparker/delve/proc.(*Variable).structMember(0x0, 0x45277ab, 0x2, 0x40, 0x40, 0xffffffffffffffff)
	/Users/jyuan/projects/gopath/src/github.com/derekparker/delve/proc/variables.go:608 +0x3a
github.com/derekparker/delve/proc.(*Variable).toFieldNamed(0x0, 0x45277ab, 0x2, 0x0)
	/Users/jyuan/projects/gopath/src/github.com/derekparker/delve/proc/variables.go:406 +0x43
github.com/derekparker/delve/proc.(*Variable).parseG(0xc43ab02380, 0xc43ab02380, 0x0, 0x0)
	/Users/jyuan/projects/gopath/src/github.com/derekparker/delve/proc/variables.go:377 +0x249
github.com/derekparker/delve/proc.(*Thread).GetG(0xc420018c80, 0xc420018c80, 0x1, 0x0)
	/Users/jyuan/projects/gopath/src/github.com/derekparker/delve/proc/threads.go:388 +0x50
github.com/derekparker/delve/proc.(*Thread).SetCurrentBreakpoint(0xc420018c80, 0xc42331c7e0, 0x0)
	/Users/jyuan/projects/gopath/src/github.com/derekparker/delve/proc/threads.go:445 +0x141
github.com/derekparker/delve/proc.(*Process).setCurrentBreakpoints(0xc42016e000, 0xc420018c80, 0x0, 0x0)
	/Users/jyuan/projects/gopath/src/github.com/derekparker/delve/proc/proc_darwin.go:454 +0x64
github.com/derekparker/delve/proc.(*Process).Continue(0xc42016e000, 0x1, 0x1)
	/Users/jyuan/projects/gopath/src/github.com/derekparker/delve/proc/proc.go:345 +0x180
github.com/derekparker/delve/service/debugger.(*Debugger).Command(0xc4200d7640, 0xc42331e760, 0x0, 0x0, 0x0)
	/Users/jyuan/projects/gopath/src/github.com/derekparker/delve/service/debugger/debugger.go:398 +0x7b9
github.com/derekparker/delve/service/rpc1.(*RPCServer).Command(0xc4235fc5c0, 0xc42331e760, 0x6aa38e8, 0xc43ab00180)
	/Users/jyuan/projects/gopath/src/github.com/derekparker/delve/service/rpc1/server.go:52 +0x39
reflect.Value.call(0xc4235f8f00, 0xc42013c098, 0x13, 0x4528059, 0x4, 0xc4233180f0, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.7.3/libexec/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xc4235f8f00, 0xc42013c098, 0x13, 0xc4233180f0, 0x3, 0x3, 0xc42332a4d0, 0x67, 0x0)
	/usr/local/Cellar/go/1.7.3/libexec/src/reflect/value.go:302 +0xa4
created by github.com/derekparker/delve/service/rpccommon.(*ServerImpl).serveJSONCodec
	/Users/jyuan/projects/gopath/src/github.com/derekparker/delve/service/rpccommon/server.go:299 +0xa38

Process finished with exit code 2

7. Others:
Idea 2016.3 + Go plugin.

Thanks,
James.

**Comment by aarzilli** [comment] 2016-12-05 15:14
go1.7 under macOS 10.12.1 can produce incorrect DWARF info, see: golang/go#17897.

To verify that this is the problem install GNU objdump with homebrew, then run `gobjdump --dwarf` on your executable and post what follows this section:

```
 <1><3b4d4>: Abbrev Number: 21 (DW_TAG_structure_type)
    <3b4d5>   DW_AT_name        : runtime.g
    <3b4df>   DW_AT_byte_size   : 400
    <3b4e1>   Unknown AT value: 2900: 25
```

**Comment by ignatov** [comment] 2017-02-28 05:44
@aarzilli Do you have any estimates?

**Comment by aarzilli** [comment] 2017-02-28 11:17
@ignatov as far as I know this is a problem with either go1.7 or macOS system linker, without the output of gobjdump I don't even know if I'm right. Unless I get more feedback I'll close this issue in a month or so.

**Comment by aarzilli** [comment] 2017-04-19 06:35
Closing, no feedback from the user likely caused by a bug in either go1.7 or old version of macOS system linker -- both of which have now been superseded by newer versions.

**Closed by aarzilli** 2017-04-19 06:35 UTC
