### ISSUE TITLE
Delve not installing on Dragonboard (Ubuntu Core in Classic mode)

### ISSUE THREAD

**Issue by lkelemen** [derekparker/delve#1361] opened 2018-10-02 12:04 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.1.0 cloned but not installing so I'm not sure:)

2. What version of Go are you using? (`go version`)?
go1.10.1 linux/arm64

3. What operating system and processor architecture are you using?
Ubuntu Core 16 Arm64 on Dragonboard

4. What did you do?
git clone https://github.com/derekparker/delve.git $GOPATH/src/github.com/derekparker/delve
cd $GOPATH/src/github.com/derekparker/delve
make install

5. What did you expect to see?
make install is successful

6. What did you see instead?
go install "-ldflags=-X main.Build=79a0e216ab2650c3460afbd87668fa38be9fffb2" github.com/derekparker/delve/cmd/dlv
\# github.com/derekparker/delve/pkg/proc
pkg/proc/disasm.go:12:14: undefined: archInst
exit status 1
Makefile:10: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by aarzilli** [comment] 2018-10-02 12:48
Duplicate of #118

**Closed by aarzilli** 2018-10-02 12:48 UTC
