### ISSUE TITLE
Cannot connect to the process twice

### ISSUE THREAD

**Issue by zolotov** [derekparker/delve#1159] opened 2018-03-21 16:11 UTC
```
package main

import (
	"time"
	"fmt"
)

func main() {
	for {
		d, _ := time.ParseDuration("3s")
		time.Sleep(d)
		fmt.Print("Hello")
	}
}
```

1. Run process `dlv debug --headless --listen=:2345 --api-version=2 main.go`
2. Connect with Delve `dlv connect localhost:2345` and run `c` command
3. Ctrl+C to stop then Ctrl+D to detach
4. Try to connect with Delve one more time `dlv connect localhost:2345`

Expected: connection successfull

Actual: `dialing:dial tcp [::1]:2345: getsockopt: connection refused`

One more thing. After detach (step 3) the program is on the pause, I'd say it makes sense to continue execution when all clients are disconnected.

1. dlv 1.1.0-rc1
2. go 1.10
3. Linux

**Comment by aarzilli** [comment] 2018-03-21 16:36
Yes, that's how it's designed to work. Headless mode is just intended to (1) let you run client and backend on different machines, (2) make life easier for people writing alternative UIs for delve. When you quit the client (Ctrl-D doesn't detach, it sends EOF causing the client to quit) the headless instance also quits.

**Comment by zolotov** [comment] 2018-03-21 17:00
@aarzilli I also cannot connect again after sending proper `DetachIn{false}` event. What's the right way to handle this in the "alternative" UI?

**Comment by aarzilli** [comment] 2018-03-21 17:06
If you want to restart the target there's the Restart request, otherwise if you disconnect you have to restart the headless session too. I'm not ruling out any change here, but I also don't understand what the use case is.

**Comment by zolotov** [comment] 2018-03-21 17:29
@aarzilli the use case is to resume debugging if client died (intentionally or accidentally), I don't understand why to restrict reconnection here.
Also, detaching often leaves the headless session in an inconsistent state: debugging session is on pause and without an ability to reconnect you cannot fix it, but detaching != intention to stop running application.

**Comment by aarzilli** [comment] 2018-03-21 17:42
> @aarzilli the use case is to resume debugging if client died (intentionally or accidentally), I don't understand why to restrict reconnection here.

it was just never meant to do that, it could be changed.

> Also, detaching often leaves the headless session in an inconsistent state: debugging session is on pause and without an ability to reconnect you cannot fix it

Do you have a way to reproduce this? In theory if the client disconnects the target should be killed and the headless instance should quit, it shouldn't stay in an inconsistent state.

**Comment by zolotov** [comment] 2018-03-21 17:56
> In theory if the client disconnects the target should be killed and the headless instance should quit, it shouldn't stay in an inconsistent state.

The steps in the issue can help with recreating. Headless instance doesn't quit.

Actually, I think it's good that headless instance isn't quit. There is also a `Kill` option in `Detach` command, and it seems reasonable to use `Kill=false` for remote debugging sessions that were not run debugging only. For example, you may want to always run your web application via Delve and sometimes to attach with Delve-client to it, debug something and detach from it. Web app should still be alive.

**Comment by aarzilli** [comment] 2018-03-21 20:24
> The steps in the issue can help with recreating. Headless instance doesn't quit.

I can't reproduce it with a simple program that calls `time.Sleep`.

> Actually, I think it's good that headless instance isn't quit. There is also a Kill option in Detach command, and it seems reasonable to use Kill=false for remote debugging sessions that were not run debugging only

Detach is to be interpreted as "detach from the target" not "detach the client from the backend".

> For example, you may want to always run your web application via Delve and sometimes to attach with Delve-client to it, debug something and detach from it. Web app should still be alive.

That's similar to #952, it can be done with some API enhancements.

**Comment by zolotov** [comment] 2018-03-23 12:18
> I can't reproduce it with a simple program that calls time.Sleep.

This is the messages that I send to delve:

```
OUT: {"method":"RPCServer.ListSources","params":[{}],"id":1}
IN: {"id":1,"result":{"Sources":[/* a lot of sources */]},"error":null}
OUT: {"method":"RPCServer.Command","params":[{"Name":"continue"}],"id":2}
OUT: {"method":"RPCServer.Command","params":[{"Name":"halt"}],"id":3}
IN: {"id":2,"result":{"State":{"currentThread":{"id":7461,"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true},"goroutineID":5},"currentGoroutine":{"id":5,"currentLoc":{"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true}},"userCurrentLoc":{"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true}},"goStatementLoc":{"pc":4485527,"file":"/home/zolotov/go/go1.10/src/runtime/time.go","line":160,"function":{"name":"runtime.(*timersBucket).addtimerLocked","value":4485264,"type":0,"goType":0,"optimized":true}},"threadID":7461},"Threads":[{"id":7461,"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true},"goroutineID":5},{"id":7479,"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true},"goroutineID":0},{"id":7480,"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true},"goroutineID":0},{"id":7482,"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true},"goroutineID":0},{"id":7483,"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true},"goroutineID":0},{"id":7484,"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true},"goroutineID":0}],"NextInProgress":false,"exited":false,"exitStatus":0,"When":""}},"error":null}
IN: {"id":3,"result":{"State":{"currentThread":{"id":7461,"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true},"goroutineID":5},"currentGoroutine":{"id":5,"currentLoc":{"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true}},"userCurrentLoc":{"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true}},"goStatementLoc":{"pc":4485527,"file":"/home/zolotov/go/go1.10/src/runtime/time.go","line":160,"function":{"name":"runtime.(*timersBucket).addtimerLocked","value":4485264,"type":0,"goType":0,"optimized":true}},"threadID":7461},"Threads":[{"id":7482,"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true},"goroutineID":0},{"id":7483,"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true},"goroutineID":0},{"id":7484,"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true},"goroutineID":0},{"id":7461,"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true},"goroutineID":5},{"id":7479,"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true},"goroutineID":0},{"id":7480,"pc":4552163,"file":"/home/zolotov/go/go1.10/src/runtime/sys_linux_amd64.s","line":527,"function":{"name":"runtime.futex","value":4552128,"type":0,"goType":0,"optimized":true},"goroutineID":0}],"NextInProgress":false,"exited":false,"exitStatus":0,"When":""}},"error":null}
OUT: {"method":"RPCServer.Detach","params":[{"Kill":false}],"id":4}
OUT: {"method":"RPCServer.Command","params":[{"Name":"continue"}],"id":5}
IN: {"id":4,"result":{},"error":null}
IN: {"id":5,"result":null,"error":"Process 7461 has exited with status 0"}
```

Notice, that `halt` is needed for detaching, otherwise, Delve doesn't respond and doesn't detach.

After that Dlv headless instance is still active, but client cannot connect to it anymore.
Debugging application with `time.Sleep` is active but halted, there is not way to continue it.

> Detach is to be interpreted as "detach from the target" not "detach the client from the backend".

I see. Then headless instance should be terminated and client should be disconnected on detach, isn't it?

> That's similar to #952, it can be done with some API enhancements.

#952 is required for the scenario I described but it's not enough. Still, client should be able to attach to the degubber several times, this is what the issue about. At the moment, I get connection refused even if client doesn't send Detach message. Is this possible to fix?

**Comment by aarzilli** [comment] 2018-03-27 15:56
> This is the messages that I send to delve:

Yes, I can get the same trace following your instructions but the headless instance does quit for me.

**Comment by zolotov** [comment] 2018-03-28 10:51
@aarzilli ok, what information do you think help you to recreate the issue?

**Comment by aarzilli** [comment] 2018-03-28 11:07
What kind of program are you debugging? Is it really the one on the opening post?

**Comment by zolotov** [comment] 2018-03-28 11:11
Yes, exact the one in the opening post.

**Comment by aarzilli** [comment] 2018-06-26 20:05
Closed by 9a216211d3461ab031f822c012bc27cab9758da0

**Closed by aarzilli** 2018-06-26 20:05 UTC

**Comment by praveenraj1987** [comment] 2018-06-27 16:45
I ran into the same issue. Glad that it got closed so soon. Thanks for the fix.

**Comment by Davidrjx** [comment] 2022-07-30 04:46
similat issue but in my case error was 
```
...
2022-07-30T12:44:55+08:00 error layer=rpc writing response:write tcp 127.0.0.1:43101->127.0.0.1:49752: use of closed network connection
```
at my client, CRTL + c  and q, then quit this client  and reconnect
