### ISSUE TITLE
=>no source available

### ISSUE THREAD

**Issue by britannic** [derekparker/delve#385] opened 2016-01-30 19:55 UTC
Delve Debugger
Version: 0.11.0-alpha
Build: d756eba13a4fbde34cea847276b3f5ce044ce916

OS X 10.11.3

Debugging any *.go program (dlv debug hello.go) and using "ls" to list source, displays:

(dlv) ls
Stopped at: 0x7fff68e39000
=>no source available

Other errors:
(dlv) break 13
Command failed: could not determine current location (scope is nil)
(dlv) ls 13
Command failed: could not determine current location (scope is nil)
(dlv) 
=========

What is required to display source code?

**Comment by aarzilli** [comment] 2016-01-30 20:13
set a breakpoint using the filename `break hello.go:13` or a function name `break main.main` then `continue`. Once the breakpoint is hit the other commands will work, it's just that you aren't stopped at a meaningful address.

Duplicate of #374.

**Comment by britannic** [comment] 2016-01-30 20:15
Brilliant, that wasn't clear to me in the write up. Thanks for the rapid follow up!

**Comment by aarzilli** [comment] 2016-01-30 20:20
No problem.

**Closed by aarzilli** 2016-01-30 20:20 UTC
