### ISSUE TITLE
Can't debug github.com/drone/drone

### ISSUE THREAD

**Issue by ignatov** [derekparker/delve#294] opened 2015-11-19 10:46 UTC
```
/usr/local/Cellar/go/1.5.1/libexec/bin/go build -o "/private/var/folders/p6/tg8pmz4509z5236gz3lprynh0000gq/T/Build drone.go and run7go" -gcflags "-N -l" /Users/ignatov/src/gocode/src/github.com/drone/drone/drone.go
/Users/ignatov/src/go/build/idea-sandbox/plugins/Go/lib/dlv/mac/dlv --listen=localhost:65233 --headless=true exec "/private/var/folders/p6/tg8pmz4509z5236gz3lprynh0000gq/T/Build drone.go and run7go" --
runtime: function symbol table header: 0x0 0x0 0x0 0x0 0x0
fatal error: invalid function symbol table

runtime: panic before malloc heap initialized

runtime stack:
```

Mac OS X 10.11.1, the latest version of delve

**Comment by gtaylor** [comment] 2015-11-19 17:23
Also seeing on this on Ubuntu Linux 15.10 with go 1.5.1 on Drone 0.4.

**Comment by aarzilli** [comment] 2015-12-30 14:27
@gtaylor does it happen systematically or only sometimes? I can't reproduce this on linux.

**Comment by gtaylor** [comment] 2016-01-03 23:44
Looking very spotty at the moment. I can't figure out any patterns. It's been working all day, but my latest debugger run showed the behavior again. Reverting the code doesn't seem to fix it.

**Comment by gtaylor** [comment] 2016-01-03 23:47
I did notice that we've got some processes hanging around. These were launched by PyCharm and the golang-idea plugin:

```
$ ps aux | grep github
greg.ta+ 31488  100  0.0 200640 10388 ?        Rl   15:36   8:50 /tmp/github7go
greg.ta+ 32516  100  0.0 200640  9848 ?        Rl   15:43   1:28 /tmp/github11go
greg.ta+ 32699  101  0.0 275684 12400 ?        Rl   15:44   0:27 /tmp/github11go
```

The appearance of these roughly coincides with when the breakage re-occured.

**Comment by derekparker** [comment] 2017-05-08 23:03
Closing, please reopen if still an active issue.

**Closed by derekparker** 2017-05-08 23:03 UTC
Labels: area/proc, kind/bug, priority/P0
