### ISSUE TITLE
Printing variable doesn't show correct value

### ISSUE THREAD

**Issue by gotschmarcel** [derekparker/delve#534] opened 2016-05-16 16:30 UTC
---

1. dlv Version: 0.11.0-alpha
2. go 1.6.2 darwin/amd64
3. OSX El Capitan, i7
4. `dlv test <pkg>` stepped into some functions and `p variable`
5. Variable is of type string and has the value `"/"`
6. dlv printed an empty string instead

---

The variable is also assigned to another variable which, when printed, shows the correct value.

**Comment by gotschmarcel** [comment] 2016-05-16 16:36
After some more testing it seems that it displays an old value. After running through the function in a loop it always prints the last value for this variable. All other variables seem to work.

**Comment by aarzilli** [comment] 2016-05-16 17:03
Without seeing the body of the function it's hard to say what could be going wrong, could be delve but it could also be the compiler. If the variable is aliased you could run into this problem. Try `locals` to see if the variable is listed multiple times.

**Comment by gotschmarcel** [comment] 2016-05-16 17:07
If i run locals it prints the name twice. The body is something like this:

```
a := returnString()

...

for _, v := range values {
  a := returnString()
  ...
}

...
```

`a` is defined at the top of the function and in the for loop. But shouldn't the variable inside of the for loop only be visible when I'm inside of the loop?

**Comment by aarzilli** [comment] 2016-05-16 17:55
> But shouldn't the variable inside of the for loop only be visible when I'm inside of the loop?

Yes, but the compiler omits to save this detail in the executable.

If you use locals you should see one of the variables keep the initial value (set outside the for loop) and the other be updated with the value set in the loop. If you can verify that that's the case this is a duplicate of #106.

**Comment by gotschmarcel** [comment] 2016-05-16 18:05
That B**** :P. Thanks for the explanation!

**Comment by aarzilli** [comment] 2016-05-16 18:15
Duplicate of #106.

**Closed by aarzilli** 2016-05-16 18:15 UTC
Labels: missing details
