### ISSUE TITLE
Source not readable 

### ISSUE THREAD

**Issue by jtestard** [derekparker/delve#1017] opened 2017-11-16 00:12 UTC
1. What version of Delve are you using (`dlv version`)?
```
└──➤ dlv version
Delve Debugger
Version: 1.0.0-rc.2
Build: a5b230b81d0d23bf3f0681235de6bb90d6a956d0
```
2. What version of Go are you using? (`go version`)?
```
go version go1.9.2 darwin/amd64
```
3. What operating system and processor architecture are you using?
<img width="254" alt="screen shot 2017-11-15 at 4 05 42 pm" src="https://user-images.githubusercontent.com/2795594/32866924-03d7da7c-ca1f-11e7-8e0d-e652591e26c1.png">

4. What did you do?

My debug session looked like this:

```
└──➤ make debug TEST_SCOPE=./controller/api/...
Generating mocks
/Library/Developer/CommandLineTools/usr/bin/make ARCH_EXT= -C /MyProject/mocks build-mocks
Beginning unit run with the following settings:
TEST_SCOPE=./controller/api/...
TEST_FLAGS=     # "-v" verbose output, "--short" to skip lengthy integration tests

Type 'help' for list of commands.
(dlv) b api_test.go:9
Command failed: no code at /MyProject/controller/api/api_test.go:9
(dlv) funcs getTestAPI
MyProject/controller/api.getTestAPI
(dlv) b MyProject/controller/api.getTestAPI
Breakpoint 1 set at 0x581294b for MyProject/controller/api.getTestAPI() ./controller/api/api_test.go:53056937
(dlv) c
> MyProject/controller/api.getTestAPI() ./controller/api/api_test.go:53056937 (hits goroutine(14):1 total:1) (PC: 0x581294b)
(dlv) args
m = MyProject/controller/manager.Manager(*MyProject/mocks/controller/mock_manager.MockManager) 0xc420043b20
~r1 = (*MyProject/controller/api.API)(0x2)
~r2 = (unreadable invalid interface type)
(dlv) ls
> MyProject/controller/api.getTestAPI() ./controller/api/api_test.go:53056937 (hits goroutine(14):1 total:1) (PC: 0x581294b)
(dlv) n
> MyProject/controller/api.getTestAPI() ./controller/api/api_test.go:53056938 (PC: 0x5812986)
(dlv) n
> MyProject/controller/api.getTestAPI() ./controller/api/api_test.go:53056940 (PC: 0x581298f)
(dlv) p config
MyProject/controller/api.Config {
	...
  ListenAddr: ...}
```

So far, I am:

 - Print the list of available functions
 - Set a breakpoint on a function
 - Move forward

But I am not able to:
 - Set a breakpoint on a line of code (even if this line of code is the first line of a function I am able to set a breakpoint on)
 - List code

5. What did you expect to see?

When I did `(dlv) ls`, I expected to see something like:

```
(dlv) ls
   7:
   8:
=>9:
   10:
   11:
```

6. What did you see instead?

```
(dlv) ls
> MyProject/controller/api.getTestAPI() ./controller/api/api_test.go:53056937 (hits goroutine(14):1 total:1) (PC: 0x581294b)
```

**Comment by aarzilli** [comment] 2017-11-16 09:03
If you are using cgo this is a duplicate of #1008

**Comment by jtestard** [comment] 2017-11-16 19:15
I am not using cgo directly, or if I am, it is deep in the dependencies. I am using the go dev version this time, and I get the same result:

```
└──➤ go version
go version devel +7edb721fbc Thu Nov 16 18:42:02 2017 +0000 darwin/amd64
```

This go version was built from source from master as of Nov 16th.

Got this
```
(dlv) b interlock.go:29
Command failed: no code at /Users/docker/go/src/github.com/docker/orca/controller/api/interlock.go:29
```

Was expecting something like

```
(dlv) b interlock.go:29
   27:
   28: func  (a *API) getConfigAndStatus(...)
   29:  client := a.manager.ProxyClient()
   30:
   31:
```

**Comment by aarzilli** [comment] 2017-11-16 19:19
What does it say if you do `b API.getConfigAndStatus`? Can I see the built binary?

**Comment by jakublipinski** [comment] 2017-11-20 11:39
I'm having the same issue (mismatch between real code line numbers and those shown by `delve`) while trying to debug `go-ethereum`. Did you fix your issue @jtestard?

**Comment by jtestard** [comment] 2017-11-20 22:11
Still working on it. Will update ASAP.

**Comment by aarzilli** [comment] 2018-03-03 12:32
Closing, no feedback.

**Closed by aarzilli** 2018-03-03 12:32 UTC
Labels: kind/needs more info, os/OSX
