### ISSUE TITLE
dlv headless server consuming 100% CPU

### ISSUE THREAD

**Issue by lafolle** [derekparker/delve#1149] opened 2018-03-10 17:09 UTC
1. What version of Delve are you using (`dlv version`)?
Master on commit 449b3cedef856ffee0adceaf497f366a245c6ba.

2. What version of Go are you using? (`go version`)?
go version go1.10 linux/amd64

3. What operating system and processor architecture are you using?
Linux yoss 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

4. What did you do?
I'm working on a core dump to debug a production issue.

To have more control over processing goroutines data in core dump, I started the dlv server in headless mode and issued RPC commands to it via RPC client present in repo.  After a minute or so,  the client got stuck on receiving a reply from server and `dlv` server started consuming 100% of cpu.
This is my interaction with dlv server:
```
glsStartTime := time.Now()
gls, err := client.ListGoroutines()
if err != nil {
	log.Fatal("fail:ListGoroutines-", err)
}
fmt.Printf("ListGoroutines: %d goroutines in %s\n", len(gls), time.Since(glsStartTime))

config := &api.LoadConfig{
	FollowPointers:     true,
	MaxVariableRecurse: 5,
	MaxStringLen:       64,
	MaxArrayValues:     64,
	MaxStructFields:    20,
}
for _, g := range gls {
	stackframes, err := client.Stacktrace(g.ID, 10, config)
	if err != nil {
		fmt.Printf("failed to get stackframes for g %d with error %s\n", g.ID, err)
		continue
	}

	// 2nd frame should be pingloop.
	if len(stackframes) < 3 {
		continue
	}
	fn := stackframes[2].Location.Function
	if fn == nil {
		continue
	}
	if !strings.Contains(fn.Name, "pingLoop") {
		continue
	}
	fmt.Println("#####frame [%d]:", g.ID, stackframes[2].Location.Function.Name)
}
```

`dlv` server is running using the following command:
```
dlv --listen "localhost:9222" --headless --accept-multiclient core hub hub.gcore.21241
```
5. What did you expect to see?
I expected to get filtered list of goroutines from RPC client.

6. What did you see instead?
After 6 results (ie goroutines I was interested in),  the client got stuck on waiting for a reply from dlv server,  which is shown by following call stack:

```
(dlv) bt
0  0x000000000042d1ea in runtime.gopark
   at /usr/local/go/src/runtime/proc.go:292
1  0x000000000042d29e in runtime.goparkunlock
   at /usr/local/go/src/runtime/proc.go:297
2  0x0000000000406312 in runtime.chanrecv
   at /usr/local/go/src/runtime/chan.go:518
3  0x0000000000405fcb in runtime.chanrecv1
   at /usr/local/go/src/runtime/chan.go:400
4  0x00000000006d132c in net/rpc.(*Client).Call
   at /usr/local/go/src/net/rpc/client.go:317
5  0x00000000006f6f48 in github.com/derekparker/delve/service/rpc2.(*RPCClient).call
   at /home/lafolle/src/github.com/derekparker/delve/service/rpc2/client.go:352
6  0x00000000006f6541 in github.com/derekparker/delve/service/rpc2.(*RPCClient).Stacktrace
   at /home/lafolle/src/github.com/derekparker/delve/service/rpc2/client.go:286
7  0x00000000006f8369 in main.main
   at /home/lafolle/src/delve/cmd/flex/main.go:101
8  0x000000000042cd92 in runtime.main
   at /usr/local/go/src/runtime/proc.go:198
9  0x00000000004571f1 in runtime.goexit
   at /usr/local/go/src/runtime/asm_amd64.s:2361
```
While server started consuming 100% CPU until forecebly killed.  `perf top` showed `99.23%  [.] github.com/derekparker/delve/pkg/proc.(*memCache).ReadMemory` .  This is what the stack trace of goroutine stuck on "ReadMemory" looks like:
```
(dlv) bt
 0  0x000000000065d3b7 in github.com/derekparker/delve/pkg/proc.(*memCache).ReadMemory
    at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/mem.go:35
 1  0x000000000065d48d in github.com/derekparker/delve/pkg/proc.(*memCache).ReadMemory
    at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/mem.go:41
 2  0x000000000065d48d in github.com/derekparker/delve/pkg/proc.(*memCache).ReadMemory
    at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/mem.go:41
 3  0x000000000065d48d in github.com/derekparker/delve/pkg/proc.(*memCache).ReadMemory
    at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/mem.go:41
 4  0x000000000065d48d in github.com/derekparker/delve/pkg/proc.(*memCache).ReadMemory
    at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/mem.go:41
 5  0x000000000065d48d in github.com/derekparker/delve/pkg/proc.(*memCache).ReadMemory
    at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/mem.go:41
 6  0x000000000065d48d in github.com/derekparker/delve/pkg/proc.(*memCache).ReadMemory
    at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/mem.go:41
 7  0x000000000065d48d in github.com/derekparker/delve/pkg/proc.(*memCache).ReadMemory
    at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/mem.go:41
 8  0x000000000065d48d in github.com/derekparker/delve/pkg/proc.(*memCache).ReadMemory
    at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/mem.go:41
 9  0x000000000065d48d in github.com/derekparker/delve/pkg/proc.(*memCache).ReadMemory
    at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/mem.go:41
10  0x000000000065d48d in github.com/derekparker/delve/pkg/proc.(*memCache).ReadMemory
    at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/mem.go:41
```
There are at least 80k frames in its stack,  but *not all* are on "ReadMemory".  After around 45k,  i see these frames:
```
44987  0x000000000067149a in github.com/derekparker/delve/pkg/proc.fieldToType
       at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/types.go:729
44988  0x000000000066fbc4 in github.com/derekparker/delve/pkg/proc.nameOfUnnamedRuntimeType
       at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/types.go:490
44989  0x000000000066ef57 in github.com/derekparker/delve/pkg/proc.nameOfRuntimeType
       at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/types.go:371
44990  0x0000000000671038 in github.com/derekparker/delve/pkg/proc.nameOfStructRuntimeType
       at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/types.go:689
44991  0x000000000066fc80 in github.com/derekparker/delve/pkg/proc.nameOfUnnamedRuntimeType
       at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/types.go:502
44992  0x000000000066ef57 in github.com/derekparker/delve/pkg/proc.nameOfRuntimeType
       at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/types.go:371
44993  0x000000000067149a in github.com/derekparker/delve/pkg/proc.fieldToType
       at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/types.go:729
44994  0x000000000066fbc4 in github.com/derekparker/delve/pkg/proc.nameOfUnnamedRuntimeType
       at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/types.go:490
44995  0x000000000066ef57 in github.com/derekparker/delve/pkg/proc.nameOfRuntimeType
       at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/types.go:371
44996  0x0000000000671038 in github.com/derekparker/delve/pkg/proc.nameOfStructRuntimeType
       at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/types.go:689
44997  0x000000000066fc80 in github.com/derekparker/delve/pkg/proc.nameOfUnnamedRuntimeType
       at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/types.go:502
44998  0x000000000066ef57 in github.com/derekparker/delve/pkg/proc.nameOfRuntimeType
       at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/types.go:371
44999  0x000000000067149a in github.com/derekparker/delve/pkg/proc.fieldToType
       at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/types.go:729
45000  0x000000000066fbc4 in github.com/derekparker/delve/pkg/proc.nameOfUnnamedRuntimeType
       at /home/lafolle/src/github.com/derekparker/delve/pkg/proc/types.go:490
```

Let me know if more data is required.  This whole thing is easily reproducible (though i don't have any contrieved sample).

Thanks,
Karan

**Comment by aarzilli** [comment] 2018-03-11 16:50
This is going to be complicated:

```
cd $GOPATH/src/github.com/derekparker/delve
git remote add aarzilli_origin https://github.com/aarzilli/delve.git
git fetch aarzilli_origin
git checkout -b inv1149 aarzilli_origin/inv1149
make build
./dlv --listen "localhost:9222" --headless --accept-multiclient core hub hub.gcore.21241
```

then run your program and tell me what happens. It looks like we are having a lot of trouble parsing a type from the runtime. Can you see if it also happens on a live program or just a coredump?

**Comment by lafolle** [comment] 2018-03-12 06:34
Core has around 67k goroutines,  and as I am iterating over each one (to inspect 3rd frame),  your modification generates lots of output.

I have figured out the goroutine on which issuing `StackTrace` triggers the problem.  This is reproducible,  though only from RPC client and not from TUI.

Here is the output:
```
lafolle@yoss:~/debug/rts/again-increasing-workers$ ~/src/delve/dlv --listen "localhost:9222" --headless --accept-multiclient core hub hub.gcore.21241
API server listening at: 127.0.0.1:9222
inteface variable "arg" searching for name of (concrete) type at 0xc21820 ("*runtime.pollDesc")
        done "*runtime.pollDesc"
inteface variable "arg" searching for name of (concrete) type at 0xc21820 ("*runtime.pollDesc")
        done "*runtime.pollDesc"
inteface variable "arg" searching for name of (concrete) type at 0xc21820 ("*runtime.pollDesc")
        done "*runtime.pollDesc"
inteface variable "arg" searching for name of (concrete) type at 0xc21820 ("*runtime.pollDesc")
        done "*runtime.pollDesc"
inteface variable "arg" searching for name of (concrete) type at 0xc21820 ("*runtime.pollDesc")
        done "*runtime.pollDesc"
inteface variable "arg" searching for name of (concrete) type at 0xc21820 ("*runtime.pollDesc")
        done "*runtime.pollDesc"
inteface variable "arg" searching for name of (concrete) type at 0xc21820 ("*runtime.pollDesc")
        done "*runtime.pollDesc"
inteface variable "arg" searching for name of (concrete) type at 0xc21820 ("*runtime.pollDesc")
        done "*runtime.pollDesc"
inteface variable "arg" searching for name of (concrete) type at 0xc21820 ("*runtime.pollDesc")
        done "*runtime.pollDesc"
inteface variable "arg" searching for name of (concrete) type at 0xc21820 ("*runtime.pollDesc")
        done "*runtime.pollDesc"
inteface variable "arg" searching for name of (concrete) type at 0xc21820 ("*runtime.pollDesc")
        done "*runtime.pollDesc"
inteface variable "arg" searching for name of (concrete) type at 0xc21820 ("*runtime.pollDesc")
        done "*runtime.pollDesc"
inteface variable "arg" searching for name of (concrete) type at 0xc21820 ("*runtime.pollDesc")
        done "*runtime.pollDesc"
inteface variable "arg" searching for name of (concrete) type at 0xc21820 ("*runtime.pollDesc")
        done "*runtime.pollDesc"
inteface variable "laddr" searching for name of (concrete) type at 0xcffa00 ("*net.TCPAddr")
        done "*net.TCPAddr"
inteface variable "laddr" searching for name of (concrete) type at 0x2444c74808244489 ("")
inteface variable "raddr" searching for name of (concrete) type at 0x8 ("")
inteface variable "err" searching for name of (concrete) type at 0xc436262580 ("error key not found\n")
inteface variable "laddr" searching for name of (concrete) type at 0xcffa00 ("*net.TCPAddr")
        done "*net.TCPAddr"
inteface variable "~r1" searching for name of (concrete) type at 0x484c7610613b48ff ("")
inteface variable "laddr" searching for name of (concrete) type at 0xcffa00 ("*net.TCPAddr")
        done "*net.TCPAddr"
inteface variable "~r0" searching for name of (concrete) type at 0x67d030 ("error key not found\n")
inteface variable "~r1" searching for name of (concrete) type at 0xcd1480 ("*context.valueCtx")
        done "*context.valueCtx"
inteface variable "Context" searching for name of (concrete) type at 0xcd13e0 ("*context.emptyCtx")
        done "*context.emptyCtx"
inteface variable "key" searching for name of (concrete) type at 0xc794e0 ("*http.contextKey")
        done "*net/http.contextKey"
inteface variable "val" searching for name of (concrete) type at 0xd81160 ("*http.Server")
        done "*net/http.Server"
inteface variable "Handler" searching for name of (concrete) type at 0xcfee00 ("*negroni.Negroni")
        done "*github.com/codegangsta/negroni.Negroni"
inteface variable "handler" searching for name of (concrete) type at 0xc76900 ("*negroni.Recovery")
        done "*github.com/codegangsta/negroni.Recovery"
inteface variable "out" searching for name of (concrete) type at 0xd81380 ("*os.File")
        done "*os.File"
inteface variable "handler" searching for name of (concrete) type at 0xd55500 ("*negroni.Logger")
        done "*github.com/codegangsta/negroni.Logger"
inteface variable "handler" searching for name of (concrete) type at 0xc76960 ("*negroni.Static")
        done "*github.com/codegangsta/negroni.Static"
inteface variable "" searching for name of (concrete) type at 0xc76900 ("*negroni.Recovery")
        done "*github.com/codegangsta/negroni.Recovery"
inteface variable "out" searching for name of (concrete) type at 0xd81380 ("*os.File")
        done "*os.File"
inteface variable "" searching for name of (concrete) type at 0xd55500 ("*negroni.Logger")
        done "*github.com/codegangsta/negroni.Logger"
inteface variable "out" searching for name of (concrete) type at 0xd81380 ("*os.File")
        done "*os.File"
inteface variable "" searching for name of (concrete) type at 0xc76960 ("*negroni.Static")
        done "*github.com/codegangsta/negroni.Static"
inteface variable "Dir" searching for name of (concrete) type at 0xc71560 ("*http.Dir")
        done "net/http.Dir"
inteface variable "" searching for name of (concrete) type at 0xd18a60 ("*cors.Cors")
        done "*github.com/rs/cors.Cors"
inteface variable "" searching for name of (concrete) type at 0xc76960 ("*negroni.Static")
        done "*github.com/codegangsta/negroni.Static"
inteface variable "Dir" searching for name of (concrete) type at 0xc71560 ("*http.Dir")
        done "net/http.Dir"
inteface variable "" searching for name of (concrete) type at 0xca6800 ("*negroni.HandlerFunc")
        done "github.com/codegangsta/negroni.HandlerFunc"
inteface variable "" searching for name of (concrete) type at 0xd18e60 ("*net.TCPListener")
        done "*net.TCPListener"
inteface variable "laddr" searching for name of (concrete) type at 0xcffa00 ("*net.TCPAddr")
        done "*net.TCPAddr"
inteface variable "PublicKey" searching for name of (concrete) type at 0x28 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x196c2000196c20 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000028 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000028 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000010 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000028 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000018 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000018 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000010 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000010 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x28 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x18711000187110 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000028 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000028 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000010 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000028 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000018 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000018 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000010 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000010 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x28 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x19725000197250 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000028 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000028 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000010 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000028 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000018 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000018 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000010 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x44c7480000000010 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x28 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x3a7880003a7880 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x282444c748 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x4c8b481824448b48 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0xfffff8250c8b4864 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x302444c748282444 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0xfffff8250c8b4864 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x14024ac89480000 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x1682484 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0xfffff8250c8b4864 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x8b483024548b4828 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x786520746f6e2073 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0xe3f633 ("error EOF\n")
inteface variable "PublicKey" searching for name of (concrete) type at 0xdb7815 ("error EOF\n")
inteface variable "PublicKey" searching for name of (concrete) type at 0xe3f633 ("error EOF\n")
inteface variable "PublicKey" searching for name of (concrete) type at 0xdbb750 ("error EOF\n")
inteface variable "PublicKey" searching for name of (concrete) type at 0xe3f633 ("error EOF\n")
inteface variable "PublicKey" searching for name of (concrete) type at 0xdb5dcb ("error EOF\n")
inteface variable "PublicKey" searching for name of (concrete) type at 0xe3f633 ("error EOF\n")
inteface variable "PublicKey" searching for name of (concrete) type at 0xda9636 ("error EOF\n")
inteface variable "PublicKey" searching for name of (concrete) type at 0xe3f633 ("error EOF\n")
inteface variable "PublicKey" searching for name of (concrete) type at 0x35342e ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0xe3f633 ("error EOF\n")
inteface variable "PublicKey" searching for name of (concrete) type at 0x3534312e322e3031 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x676e69703b696870 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x20732520752d200a ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x3b72726162723b6f ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0x72616d6b63656863 ("")
inteface variable "PublicKey" searching for name of (concrete) type at 0xcf64c0 ("*map.bucket[string]map[seelog.LogLevel]bool")
```

RPC client code used to get stack trace of goroutine:
```Go
	config := &api.LoadConfig{
		FollowPointers:     true,
		MaxVariableRecurse: 5,
		MaxStringLen:       64,
		MaxArrayValues:     64,
		MaxStructFields:    20,
	}
	_, err := client.Stacktrace(141, 10, config)
	if err != nil {
		fmt.Println(err)
		return
	}
```

Stack trace of goroutine 141 (which is triggering the problem) fetched from TUI
```
(dlv) goroutine 141 bt
 0  0x000000000043992c in runtime.gopark
    at /usr/local/go/src/runtime/proc.go:288
 1  0x0000000000434a3a in runtime.netpollblock
    at /usr/local/go/src/runtime/netpoll.go:366
 2  0x0000000000434037 in internal/poll.runtime_pollWait
    at /usr/local/go/src/runtime/netpoll.go:173
 3  0x00000000004a037e in internal/poll.(*pollDesc).wait
    at /usr/local/go/src/internal/poll/fd_poll_runtime.go:85
 4  0x00000000004a03fd in internal/poll.(*pollDesc).waitRead
    at /usr/local/go/src/internal/poll/fd_poll_runtime.go:90
 5  0x00000000004a2852 in internal/poll.(*FD).Accept
    at /usr/local/go/src/internal/poll/fd_unix.go:335
 6  0x0000000000576422 in net.(*netFD).accept
    at /usr/local/go/src/net/fd_unix.go:238
 7  0x000000000059285e in net.(*TCPListener).accept
    at /usr/local/go/src/net/tcpsock_posix.go:136
 8  0x0000000000590e79 in net.(*TCPListener).Accept
    at /usr/local/go/src/net/tcpsock.go:247
 9  0x0000000000686982 in net/http.(*Server).Serve
    at /usr/local/go/src/net/http/server.go:2695
10  0x0000000000b02b91 in github.com/braintree/manners.(*GracefulServer).Serve
    at /home/sajith/pubsub/_vendor/src/github.com/braintree/manners/server.go:216
(dlv)
```

Hope this is helpful.

**Comment by lafolle** [comment] 2018-03-12 06:39
> Can you see if it also happens on a live program or just a coredump?
I have to spend more time to answer this.  Though I can tell you one more thing.
I have another core dump of the same program taken at different time and different machine which does not have this problem.

In the problematic dump,  if I skip goroutine with ID 141,  everything works fine.

**Comment by aarzilli** [comment] 2018-03-12 09:35
I assume getting my hands on this coredump and its executable is impossible, right?

**Comment by aarzilli** [comment] 2018-03-12 09:49
This isn't enough to guess what's happening, if I can't see the core dump directly I'll need you to pull again from my fork and run your test again.

**Comment by lafolle** [comment] 2018-03-12 11:13
> I assume getting my hands on this coredump and its executable is impossible, right?

Sorry @aarzilli,  I'm afraid you're right.  The program under context is literally an important part of our company which implicitly handles big customers.

> This isn't enough to guess what's happening, if I can't see the core dump directly I'll need you to pull again from my fork and run your test again.

That is fine with me,  though it is going to make the process really slow.

Let's try 2 ways:
1.  As long as you're fine,  I'm willing to keep pulling your branch and answering your questions. (as you suggested)
2.  I'll try to debug it myself which might need some hand-holding from others as I'm a complete novice in the field of debuggers.

**Comment by aarzilli** [comment] 2018-03-12 11:33
> That is fine with me, though it is going to make the process really slow.

I know, but at the moment I can't come up with any good theory about this problem.

> I'll try to debug it myself which might need some hand-holding from others as I'm a complete novice in the field of debuggers.

You don't really need much domain specific knowledge for this. ReadMemory is a call that reads memory from the target process. The stack of calls to nameOfUnnamedRuntimeType/etc is trying to find the name of the concrete type of an interface variable. My current guess is that the stack of ReadMemory calls is a red herring and the problem is deep down on that stack trace and what's happening is that we are hitting a recursive type definition made with unnamed types, the problem is that I don't think there is a way in the go language to make a recursive type out of unnamed types, so it must be something else.

If you can isolate the exact interface variable that's causing this you can then step through the code that calculates its type, starting at nameOfRuntimeType and see exactly what's going on.

**Comment by aarzilli** [comment] 2018-08-30 11:37
I'm going to close this bug because (a) we can't reproduce it, (b) we couldn't figure out the exact cause, (c) the code that seems involved in causing it, i.e. the code that finds a DIE given a runtime._type, changed with go1.11 to something more robust.

**Closed by aarzilli** 2018-08-30 11:37 UTC
Labels: area/proc, kind/bug
