### ISSUE TITLE
Brew install not working

### ISSUE THREAD

**Issue by fredleger** [derekparker/delve#946] opened 2017-08-13 12:56 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
still none was a try to install it

2. What version of Go are you using? (`go version`)?
go version go1.8.3 darwin/amd64

3. What operating system and processor architecture are you using?
darwin/amd64

4. What did you do?
brew install go-delve/delve/delve

5. What did you expect to see?
Successfull install

6. What did you see instead?
Error msg
```
==> Installing delve from go-delve/delve
==> Downloading https://github.com/derekparker/delve/archive/v1.0.0-rc.1.tar.gz
Already downloaded: /Users/frederic/Library/Caches/Homebrew/delve-1.0.0-rc.1.tar.gz
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
==> Generating dlv-cert
==> openssl req -new -newkey rsa:2048 -x509 -days 3650 -nodes -config dlv-cert.cfg -extensions codesign_reqext -batch -out dlv-cer
==> [SUDO] Installing dlv-cert as root
==> sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain dlv-cert.cer
Last 15 lines from /Users/frederic/Library/Logs/Homebrew/delve/02.sudo:
2017-08-13 14:55:20 +0200

sudo
security
add-trusted-cert
-d
-r
trustRoot
-k
/Library/Keychains/System.keychain
dlv-cert.cer


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/go-delve/homebrew-delve/issues
```

**Comment by fredleger** [comment] 2017-08-13 12:56
Please not it's on MBP end 2016 with touchbar

**Comment by fredleger** [comment] 2017-08-13 12:58
```
go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/frederic/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n_/jtqch7ls28534bbt4hl905mr0000gn/T/go-build165910304=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

**Comment by aarzilli** [comment] 2017-08-13 17:49
Duplicate of https://github.com/go-delve/homebrew-delve/issues/17

**Closed by aarzilli** 2017-08-13 17:49 UTC
