### ISSUE TITLE
MacOS: cannot continue on panic

### ISSUE THREAD

**Issue by zolotov** [derekparker/delve#1371] opened 2018-10-12 16:39 UTC
Dlv commit: 74c98bc9616ad4ee324eb4d31717b61f4a6ab8ce
Go 1.11.1
macos mojave

```
ᐅ /Users/zolotov/dev/goland/build/dlv/mac/dlv  --api-version=2 exec /private/var/folders/m8/8sm6vlls2cs8xdmgs16y27zh0000gn/T/___go_build_scratch_9_go --          
Type 'help' for list of commands.
(dlv) c
=== Calling a function on a nil-pointed struct> expvar.(*Int).Value() /Users/zolotov/go/go1.11/src/expvar/expvar.go:53 (PC: 0x12cd6fc)
Command failed: bad access
(dlv) c
> expvar.(*Int).Value() /Users/zolotov/go/go1.11/src/expvar/expvar.go:53 (PC: 0x12cd6fc)
Command failed: bad access
(dlv) c
> expvar.(*Int).Value() /Users/zolotov/go/go1.11/src/expvar/expvar.go:53 (PC: 0x12cd6fc)
Command failed: bad access
(dlv) 
```

I expect the process will be terminated on the second `continue`. Like it does on Linux:

```
➜  /home/zolotov/dev/intellij-go-ide/build/dlv/linux/dlv --api-version=2 exec /tmp/___go_build_b_go -- #gosetup          
Type 'help' for list of commands.
(dlv) c
=== Calling a function on a nil-pointed struct11> [unrecovered-panic] runtime.fatalpanic() /snap/go/2635/src/runtime/panic.go:681 (hits goroutine(1):1 total:1) (PC: 0x430c50)
Warning: debugging optimized function
        runtime.curg._panic.arg: interface {}(string) "runtime error: invalid memory address or nil pointer dereference"
   676: // fatalpanic implements an unrecoverable panic. It is like fatalthrow, except
   677: // that if msgs != nil, fatalpanic also prints panic messages and decrements
   678: // runningPanicDefers once main is blocked from exiting.
   679: //
   680: //go:nosplit
=> 681: func fatalpanic(msgs *_panic) {
   682:         pc := getcallerpc()
   683:         sp := getcallersp()
   684:         gp := getg()
   685:         var docrash bool
   686:         // Switch to the system stack to avoid any stack growth, which
(dlv) c
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6cc3bc]

goroutine 1 [running]:
expvar.(*Int).Value(0x0, 0x0)
        /snap/go/2635/src/expvar/expvar.go:53 +0x1c
main.main()
        /home/zolotov/GolandProjects/go-metrics/testdata2/b/b.go:13 +0x8e
Process 29198 has exited with status 2
```

**Comment by chainhelen** [comment] 2018-10-13 06:33
Look like that get signal named `TARGET_EXC_BAD_ACCESS = 0x91` from os.

**Comment by aarzilli** [comment] 2018-10-13 16:27
This is a duplicate of #852. See also https://bugs.llvm.org/show_bug.cgi?id=22868. The easiest way to fix this would be to try to get the LLVM project to add a flag to debugserver to ignore SIGSEGV. The code change is described here:

https://stackoverflow.com/questions/26829119/how-to-make-lldb-ignore-exc-bad-access-exception

Since that's a stackoverflow link the fix might or might not work. I haven't tried it because building debugserver on my VM takes over two hours, it's just too painful. Hopefully someday somebody with access to a mac and enough patience to deal with the apples will come along.

**Closed by aarzilli** 2018-10-13 16:27 UTC

**Comment by tekumara** [comment] 2023-10-26 04:57
FYI see https://github.com/llvm/llvm-project/issues/23242
