### ISSUE TITLE
go get doesn't work

### ISSUE THREAD

**Issue by Ronacaodo** [derekparker/delve#1086] opened 2018-01-20 08:03 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv `version`)?` 
**install failed**

2. What version of Go are you using? (`go version`)?
**go version go1.9.2 windows/386**

3. What operating system and processor architecture are you using?
**win10 x64** with **Intel64 Family 6 Model 142 Stepping 9 GenuineIntel ~400 Mhz**

4. What did you do?
`go get -u github.com/derekparker/delve/cmd/dlv`

5. What did you expect to see?
**install success**

6. What did you see instead?
It hint 
`C:\Users\ronac\Documents\program\GOPATH\src>go get -u github.com/derekparker/delve/cmd/dlv

\#github.com/derekparker/delve/pkg/proc
github.com\derekparker\delve\pkg\proc\disasm.go:9:14: undefined: ArchInst`

**Comment by jayachar88** [comment] 2018-01-20 09:03
Same issue observed as above.
1. same outcome as above
2. same version of Go (1.9.2 windows/386)
3. OS and processor:
  win10 x64 (Enterprise) with AMD PRO-A10-8700B R6, 8GB RAM
4. same command as above
5. same as above
6. same error reported i.e.:
C:\Users\jayachar88\go\src\github.com\derekparker\delve\pkg\proc\disasm.go:9:14: undefined: ArchInst

**Comment by dlsniper** [comment] 2018-01-20 09:39
Install Go for amd64 instead of 386 and it will work. Delve currently does not support 386, see #20.

This is a duplicate of https://github.com/derekparker/delve/issues/1083

**Comment by Ronacaodo** [comment] 2018-01-20 10:05
@dlsniper I'm still confusing.Does my cpu was 32-bit and it couldn't use delve?

**Comment by dlsniper** [comment] 2018-01-20 10:21
> @dlsniper I'm still confusing.Does my cpu was 32-bit and it couldn't use delve?

@Ronacaodo, you are using a 64 bit operating system so your CPU supports 64bit instructions. However, the Go version you installed is for 32bit CPUs and delve does not currently support this. Reinstall Go for 64 bit anf it will work.

**Comment by Ronacaodo** [comment] 2018-01-20 10:49
@dlsniper Thanks

**Closed** 2018-01-21 18:08 UTC

**Comment by Demitroi** [comment] 2018-03-07 17:35
Try using this in console
env GOARCH=amd64 go get -u github.com/derekparker/delve/cmd/dlv

**Comment by dlsniper** [comment] 2018-03-07 17:36
it's better to use the Go for amd64 than 386 on an amd64 platform.
