### ISSUE TITLE
Command failed: bad access - when trying to debug prometheus

### ISSUE THREAD

**Issue by krasi-georgiev** [derekparker/delve#975] opened 2017-09-29 08:57 UTC
```
dlv version
Delve Debugger
Version: 1.0.0-rc.1
Build: 5c9b2009cab214c1f912a2d8c6c89eec9f3ada2b
```

```
go version
go version go1.9 darwin/amd64
```
```
OSX,Intel Core i7
```

```
~/src/../prometheus/cmd/prometheus $ dlv debug -- --config.file=/Users/krasimir/src/github.com/prometheus/prometheus/documentation/examples/prometheus.yml
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x237e841 for main.main() ./main.go:71
(dlv) c
   223:						}
   224:					}
   225:				}
   226:			}()
   227:			// intentional nil pointer dereference to trigger sigpanic
=> 228:			return *p
   229:		}()
   230:		return fn
   231:	}
   232:
   233:	var sigpanic = findSigpanic()
Command failed: bad access
(dlv)
```

5. What did you expect to see?
program state at the begining or main, after all init funcitons.
It doesn't matter where I put the breakpoint it always panics to this
```
https://github.com/prometheus/prometheus/blob/dev-2.0/vendor/github.com/go-stack/stack/stack.go#L228
```

normal start of prometheus:
```
~/src/../prometheus/cmd/prometheus $ go run main.go uname_default.go --config.file=../../documentation/examples/prometheus.ymllevel=info ts=2017-09-29T08:55:32.008383Z caller=main.go:214 msg="Starting prometheus" version="(version=, branch=, revision=)"
level=info ts=2017-09-29T08:55:32.008437Z caller=main.go:215 build_context="(go=go1.9, user=, date=)"
level=info ts=2017-09-29T08:55:32.00846Z caller=main.go:216 host_details=(darwin)
level=info ts=2017-09-29T08:55:32.010063Z caller=main.go:308 msg="Starting TSDB"
level=info ts=2017-09-29T08:55:32.010065Z caller=web.go:367 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2017-09-29T08:55:32.010087Z caller=targetmanager.go:68 component="target manager" msg="Starting target manager..."
level=info ts=2017-09-29T08:55:32.023871Z caller=main.go:320 msg="TSDB started"
level=info ts=2017-09-29T08:55:32.023917Z caller=main.go:387 msg="Loading configuration file" filename=../../documentation/examples/prometheus.yml
level=info ts=2017-09-29T08:55:32.024514Z caller=main.go:364 msg="Server is ready to receive requests."
```

**Comment by aarzilli** [comment] 2017-09-29 10:27
Duplicate of #852

**Closed by aarzilli** 2017-09-29 10:27 UTC
