### ISSUE TITLE
Delve exception on Windows

### ISSUE THREAD

**Issue by hacenator** [derekparker/delve#980] opened 2017-10-05 14:10 UTC
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0-rc.1
Build: $Id: b6077a6a35c48a31716aad2ad3fdf77bbdf70abd $

2. What version of Go are you using? (`go version`)?
go version go1.8.4 windows/amd64
or
go 1.9
or 
go 1.9.1

3. What operating system and processor architecture are you using?
Windows 10

4. What did you do?
dlv exec hello.go

5. What did you expect to see?
cli

6. What did you see instead?
```
Exception 0xc000001d 0xffffcb0d4074a7c0 0xffffcb0d4074a7c0 0x18000890d
PC=0x18000890d

syscall.Syscall(0x7ffe999ebfd0, 0x2, 0x2d4, 0x2, 0x0, 0x1e0, 0x9ab060, 0x6420756f0)
        C:/Go/src/runtime/syscall_windows.go:163 +0x69
syscall.SetFileCompletionNotificationModes(0x2d4, 0x2, 0xa097eb, 0x4)
        C:/Go/src/syscall/zsyscall_windows.go:1727 +0x6f
internal/poll.(*FD).Init(0xc042184780, 0xa097eb, 0x4, 0xa34358, 0x2d4, 0x0, 0x0)
        C:/Go/src/internal/poll/fd_windows.go:346 +0xf9
os.newFile(0x2d4, 0xc04226f080, 0x20, 0xa097eb, 0x4, 0x0)
        C:/Go/src/os/file_windows.go:57 +0x138
os.openFile(0xc04226f080, 0x20, 0x0, 0xc0000001ff, 0xc04219a300, 0xc042198200, 0xc042075820)
        C:/Go/src/os/file_windows.go:98 +0xff
os.OpenFile(0xc04226f080, 0x20, 0x0, 0x1ff, 0x0, 0x0, 0x0)
        C:/Go/src/os/file_windows.go:159 +0x15e
github.com/derekparker/delve/pkg/proc/native.openExecutablePathPE(0xc04226f080, 0x20, 0xc042265120, 0x8, 0x0, 0x0, 0x6a18a2)
        C:/Users/hacen/go/src/github.com/derekparker/delve/pkg/proc/native/proc_windows.go:27 +0x51
github.com/derekparker/delve/pkg/proc/native.Launch(0xc04204fd90, 0x1, 0x1, 0xa08465, 0x1, 0x0, 0x0, 0x0)
        C:/Users/hacen/go/src/github.com/derekparker/delve/pkg/proc/native/proc_windows.go:53 +0x14c
github.com/derekparker/delve/service/debugger.(*Debugger).Launch(0xc042168700, 0xc04204fd90, 0x1, 0x1, 0xa08465, 0x1, 0xc0042075a80, 0x48, 0x50, 0xc042164370)
        C:/Users/hacen/go/src/github.com/derekparker/delve/service/debugger/debugger.go:123 +0x2e8
github.com/derekparker/delve/service/debugger.New(0xc042164370, 0xc042164370, 0x60, 0xc042075ac8)
        C:/Users/hacen/go/src/github.com/derekparker/delve/service/debugger/debugger.go:98 +0x3fd
github.com/derekparker/delve/service/rpccommon.(*ServerImpl).Run(0xc042164320, 0xc04216a200, 0xc042164320)
        C:/Users/hacen/go/src/github.com/derekparker/delve/service/rpccommon/server.go:113 +0x134
github.com/derekparker/delve/cmd/dlv/cmds.execute(0x0, 0xc04204fd90, 0x1, 0x1, 0xc04215e180, 0x0, 0x0, 0x0, 0x0)
        C:/Users/hacen/go/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:482 +0x2ea
github.com/derekparker/delve/cmd/dlv/cmds.New.func4(0xc04220a000, 0xc04204fd90, 0x1, 0x1)
        C:/Users/hacen/go/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:173 +0x76
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).execute(0xc04220a000, 0xc04204fd50, 0x1, 0x1, 0xc04220a000, 0xc04204fd50)
        C:/Users/hacen/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:647 +0x23e
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0420db680, 0x0, 0x0, 0x0)
        C:/Users/hacen/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:733 +0x305
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0420db680, 0xc0420db680, 0x8e5d30)
        C:/Users/hacen/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:692 +0x32
main.main()
        C:/Users/hacen/go/src/github.com/derekparker/delve/cmd/dlv/main.go:15 +0x66

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
        C:/Go/src/runtime/sigqueue.go:131 +0xad
os/signal.loop()
        C:/Go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.0
        C:/Go/src/os/signal/signal_unix.go:28 +0x48
rax     0x0
rbx     0xc042046340
rcx     0x2d4
rdi     0x351000
rsi     0xc042075628
rbp     0xc0420755d8
rsp     0x240fda0
r8      0x0
r9      0x2d4
r10     0x15499e0
r11     0x152d4c8
r12     0x0
r13     0xfa
r14     0xfa
r15     0xa
rip     0x18000890d
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by aarzilli** [comment] 2017-10-05 15:01
This is similar to https://github.com/golang/go/issues/13541 the problem is with either go or your windows install.

cc @alexbrainman you may be interested in this.

**Comment by hacenator** [comment] 2017-10-05 15:29
Yes, I've seen this issue report.
Also I remembered that I had a similar problem with Docker on this PC.

**Comment by alexbrainman** [comment] 2017-10-06 00:14
@hacenator someone just reported similar issue on Go issue list. See my reply here https://github.com/golang/go/issues/22149#issuecomment-334625463

Alex

**Comment by aarzilli** [comment] 2017-10-06 05:52
Closing since it's unrelated to delve. @hacenator  you should read https://github.com/moby/moby/issues/27423 that @alexbrainman linked on the golang/go issue, search "netsh winsock show catalog" and read from there.

**Closed by aarzilli** 2017-10-06 05:52 UTC
