### ISSUE TITLE
Breakpoints linespec in Windows is case-sensitive

### ISSUE THREAD

**Issue by vornet** [derekparker/delve#373] opened 2016-01-26 13:40 UTC
When adding breakpoints, if the casing does not match exactly "d:/go_dev/src/github.com/vornet/hello/hello.go" vs "D:/go_dev/src/github.com/vornet/hello/hello.go", the breakpoint will not be added, erroring out with: Command failed: Location "xxx" not found.

On other OSes, case sensitivity is expected, but on Windows, it should not be case-sensitive.

For full filepaths, the workaround is to make sure the casing in the GOPATH (delve uses it to match full paths) matches the breakpoint linespec. So if GOPATH="D:/Go_Dev", linespec should be "D:/Go_Dev/src/...."

**Comment by jussij** [comment] 2016-01-26 13:52
I think this is the same as an issue I raised earlier: https://github.com/derekparker/delve/issues/370

**Comment by aarzilli** [comment] 2016-01-26 14:01
Closing this as duplicate of #370.

**Closed by aarzilli** 2016-01-26 14:01 UTC
