### ISSUE TITLE
Win32 panic slice bounds out of range

### ISSUE THREAD

**Issue by welemon** [derekparker/delve#443] opened 2016-03-03 19:41 UTC
This issue is noticed with intelliJ Go plugin 0.10.1164, while try to debug whole package (instead of single go file), windows dlv.exe panic saying

panic: runtime error: slice bounds out of range

goroutine 34 [running]:
github.com/derekparker/delve/dwarf/frame.parseFDE(0xc0824080c0, 0xb9ddf0)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/dwarf/frame/parser.go:74 +0x406
github.com/derekparker/delve/dwarf/frame.Parse(0xc082724000, 0x592a4, 0x59400, 0x355fe0, 0xdbb860, 0x0, 0x0, 0x0)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/dwarf/frame/parser.go:33 +0x1c8
github.com/derekparker/delve/proc.(*Process).parseDebugFrame(0xc082082540, 0xc0820f2230, 0xc0820ea980)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc_windows.go:174 +0x4df
created by github.com/derekparker/delve/proc.(*Process).LoadInformation
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc.go:154 +0x112

Same exact source code works well on Mac version of dlv.exe and go plugin.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 0.11.0-alpha
Build: 63a660820e7beef3b4870922e25897887392b188

2. What version of Go are you using? (`go version`)?
go version go1.6 windows/386

3. What operating system and processor architecture are you using?
Win32  64bit OS but golang exe and target exe is 32bit

4. What did you do?
C:/Go\bin\go.exe build -o C:\Users\leewi\AppData\Local\Temp\clm-adls0go -gcflags "-N -l" git.company.com/clm-adls
C:\Users\leewi\.IntelliJIdea15\config\plugins\Go\lib\dlv\windows\dlv.exe --listen=localhost:50958 --headless=true exec C:\Users\leewi\AppData\Local\Temp\clm-adls0go --
panic: runtime error: slice bounds out of range
...

5. What did you expect to see?
No panic and be able to debug

6. What did you see instead?
Panic and stopped debugger

**Comment by alexbrainman** [comment] 2016-04-05 02:13
It would help to see your executable file C:\Users\leewi\AppData\Local\Temp\clm-adls0go. It would be even better if you can provide instructions on how to build C:\Users\leewi\AppData\Local\Temp\clm-adls0go. Thank you.

Alex

**Comment by aarzilli** [comment] 2016-04-06 08:18
One possible explanation for that panic would be a FDE in debug_frame containing no instructions.

**Comment by lukehoban** [comment] 2016-05-29 21:49
> go version go1.6 windows/386

Looks like this is on 32-bit Go.  Pretty sure Delve doesn't support 32-bit Go installations on any platform.

**Comment by aarzilli** [comment] 2016-05-30 03:47
Ah, didn't catch that. Closing as duplicate of #20. Thanks, @lukehoban.

**Closed by aarzilli** 2016-05-30 03:47 UTC
Labels: area/dwarf, kind/bug, os/windows

**Comment by alexbrainman** [comment] 2016-05-30 14:04
> Looks like this is on 32-bit Go.

Shouldn't Delve recognize this situation and stop debugging with a nice error message, instead of confusing us all?

Alex
