### ISSUE TITLE
Installing via homebrew also installs Go via homebrew

### ISSUE THREAD

**Issue by Phlamethrower** [derekparker/delve#901] opened 2017-06-27 16:05 UTC
1. What version of Delve are you using (`dlv version`)?

homebrew package "stable 1.0.0-rc.1, HEAD"

2. What version of Go are you using? (`go version`)?

go version go1.7.6 darwin/amd64

3. What operating system and processor architecture are you using?

macOS Sierra

4. What did you do?

`$ brew install go-delve/delve/delve`

5. What did you expect to see?

go-delve installed via homebrew

6. What did you see instead?

go-delve *and* Go installed via homebrew, overwriting my install of the official Go package.

Possibly this is a bug in homebrew, or homebrew's Go package (why did it overwrite my official Go install without asking? why can't it detect official Go installations as surrogates for homebrew installations?). Possibly this is a bug in delve's package. But at the least, it would be nice to have a warning in the installation docs that the homebrew install will also install Go via homebrew.

**Comment by aarzilli** [comment] 2017-06-27 17:34
Duplicate of https://github.com/go-delve/homebrew-delve/issues/9

**Closed by aarzilli** 2017-06-27 17:34 UTC
