### ISSUE TITLE
vscode golang debugging

### ISSUE THREAD

**Issue by XieXiaomei-ptr** [derekparker/delve#1177] opened 2018-04-10 09:57 UTC
1. Delve Debugger Version: 1.0.0 Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533 $
2. go version go1.10.1 darwin/amd64
3. MacBook-Pro OS Version:OSX 10.13.3 (17D102)  CPU: 2.2 GHz Intel Core i7
4. I'm doing go programming on Vscode Version:1.22.1, and all go language plugins are installed. 
F5 to start debugging, then
2018/04/10 17:26:07 server.go:73: Using API v1
2018/04/10 17:26:07 debugger.go:98: launching process with args: [/Users/xiexiaomei/go/src/test/debug]
could not launch process: EOF
Process exiting with code: 1

I've tried to file this issue to Microsoft/vscode, but they told me to submit it here.

**Comment by dlsniper** [comment] 2018-04-10 11:02
This is a duplicate of #1165

**Closed** 2018-04-10 21:53 UTC
