### ISSUE TITLE
Unknown load command 0x32 (50)

### ISSUE THREAD

**Issue by conradwt** [derekparker/delve#1292] opened 2018-08-05 08:48 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

```
$ go get -u -v github.com/derekparker/delve/cmd/dlv
github.com/derekparker/delve (download)
# github.com/derekparker/delve/cmd/dlv
/opt/local/lib/go/pkg/tool/darwin_amd64/link: /opt/local/lib/go/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)
```

1. What version of Delve are you using (`dlv version`)?

I'm attempting to install the latest version of the software.

2. What version of Go are you using? (`go version`)?

```text
$ go version
go version go1.10.3 darwin/amd64
```

3. What operating system and processor architecture are you using?

```text
macOS 10.14 beta 5 (18A347e)

Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
```

4. What did you do?

```text
$ go get -u -v github.com/derekparker/delve/cmd/dlv
```

5. What did you expect to see?

I expected to not see any errors during installation.

6. What did you see instead?

```
github.com/derekparker/delve (download)
# github.com/derekparker/delve/cmd/dlv
/opt/local/lib/go/pkg/tool/darwin_amd64/link: /opt/local/lib/go/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)
```

**Comment by aarzilli** [comment] 2018-08-05 12:28
Duplicate of https://github.com/golang/go/issues/25908

**Closed by aarzilli** 2018-08-05 12:28 UTC
