### ISSUE TITLE
Can't set breakpoint on certain valid lines

### ISSUE THREAD

**Issue by andradei** [derekparker/delve#441] opened 2016-03-02 19:11 UTC
After running:
`thread XXXXX`
to switch the another goroutine, the command
`break file.go:xx`
produces the following error:

`Command failed: no code at /path/to/file.go:xx`

**Comment by derekparker** [comment] 2016-03-02 19:17
Did that break point command work prior to switching threads?

**Comment by andradei** [comment] 2016-03-02 19:19
Yes. After a few more tries, I found out that it is the lines that are a bit off, for example:
In my code I want the breakpoint to be on _line 29_ (which is a valid line of code), in delve I need to actually run `break file.go:30` (line + 1).

This behavior started after using delve for several minutes.

**Comment by derekparker** [comment] 2016-03-02 19:21
Do the correct line numbers _become_ invalid after a while of using Delve, or are _already_ invalid at startup?

Any chance you could submit a gist of the output of a debug session in which this happens?

**Comment by andradei** [comment] 2016-03-02 19:27
Here's how it is behaving right now. I edited the output to hide full paths.
Notice that I tried to set breakpoints at some places that are actually valid, as the output at the end shows (like line 47). But only one breakpoint worked (line 43), which I don't know why it worked versus the others.

```
(dlv) b connection.go:28
Command failed: no code at GOPATH/src/github.com/quickfixgo/quickfix/connection.go:28
(dlv) break initiator.go:47
Breakpoint 2 set at 0x7b8c5 for github.com/quickfixgo/quickfix.(*Initiator).Start GOPATH/src/github.com/quickfixgo/quickfix/initiator.go:47
(dlv) break connection.go:28
Command failed: no code at GOPATH/src/github.com/quickfixgo/quickfix/connection.go:28
(dlv) break connection.go:27
Command failed: no code at GOPATH/src/github.com/quickfixgo/quickfix/connection.go:27
(dlv) break connection.go:29
Breakpoint 3 set at 0x7067f for github.com/quickfixgo/quickfix.handleInitiatorConnection GOPATH/src/github.com/quickfixgo/quickfix/connection.go:29
(dlv) break initiator.go:47
Command failed: Breakpoint exists at GOPATH/src/github.com/quickfixgo/quickfix/initiator.go:47 at 7b8c5
(dlv) break initiator.go:48
Command failed: no code at GOPATH/github.com/quickfixgo/quickfix/initiator.go:48
(dlv) break initiator.go:46
Command failed: no code at GOPATH/src/github.com/quickfixgo/quickfix/initiator.go:46
(dlv) break initiator.go:45
Command failed: no code at GOPATH/src/github.com/quickfixgo/quickfix/initiator.go:45
(dlv) break initiator.go:44
Command failed: no code at GOPATH/src/github.com/quickfixgo/quickfix/initiator.go:44
(dlv) break initiator.go:43
Breakpoint 4 set at 0x7b8a5 for github.com/quickfixgo/quickfix.(*Initiator).Start GOPATH/src/github.com/quickfixgo/quickfix/initiator.go:43
(dlv) c
> github.com/quickfixgo/quickfix.(*Initiator).Start() GOPATH/src/github.com/quickfixgo/quickfix/initiator.go:43 (hits goroutine(1):1 total:1)
    38:			if s.HasSetting(config.SocketUseSSL) {
    39:				if certPath, err := s.Setting(config.SocketCert); err == nil {
    40:					secureConnData[0] = certPath
    41:				}
    42:				if certPass, err := s.Setting(config.SocketCertPassword); err == nil {
=>  43:					secureConnData[1] = certPass
    44:				}
    45:			}
    46:
    47:			go handleInitiatorConnection(address, i.globalLog, sessionID, i.quitChans[sessionID], secureConnData)
    48:		}

**Comment by andradei** [comment] 2016-03-02 19:34
More output detail:

```
(dlv) bp
Breakpoint 1 at 0x2508 ./main.go:28 (1)
Breakpoint 2 at 0x7b8c5 GOPATH/src/github.com/quickfixgo/quickfix/initiator.go:47 (0)
Breakpoint 3 at 0x7067f GOPATH/src/github.com/quickfixgo/quickfix/connection.go:29 (0)
Breakpoint 4 at 0x7b8a5 GOPATH/src/github.com/quickfixgo/quickfix/initiator.go:43 (1)
```

So delve said the breakpoint at line 47 failed, but it is listed as one of the breakpoints.

**Comment by derekparker** [comment] 2016-03-02 19:39
This actually seems like reasonable behavior. In the instances the `break` command seems to fail, it's because you're trying to set a break point on the closing bracket of a block, which technically doesn't exist except for in the source code (does not compile into any instructions), so there really isn't anywhere to set a break point.

IIRC GDB may try and "figure it out" by setting a break point on the next line, but that information is not actually encoded into the debug info line table.

Also, with regard to your last post with more detail, looking at the original output you posted the break point on line 47 did actually succeed, and then you attempted to set another break point there and that's when it complained.

**Comment by andradei** [comment] 2016-03-02 19:41
Actually. Let me apologize, the program is running as expected right? Line 47 was set before (according to the output), I didn't know that a `restart` would keep the breakpoints around.

Also, other attempts like `b connection.go:27` and `b connection.go:28` are an empty line, an `if` declaration respectively. I was under the impression a breakpoint could be set on `if condition {` lines.

I believe everything is working fine with breakpoints.

**Comment by derekparker** [comment] 2016-03-02 19:43
@andradei you should be able to set a break point on the _conditional_ line of an if statement, i.e. the actual source line where `if <condition> {` occurs, just not the closing bracket.

**Comment by andradei** [comment] 2016-03-02 19:48
Hmmm.
Am I missing something?

<img width="569" alt="screen shot 2016-03-02 at 12 46 13 1" src="https://cloud.githubusercontent.com/assets/2653546/13473051/da52321e-e074-11e5-8228-3053b7c32be3.png">

```
(dlv) b connection.go:28
Command failed: no code at GOPATH/src/github.com/quickfixgo/quickfix/connection.go:28
(dlv) b connection.go:29
Breakpoint 1 set at 0x7067f for github.com/quickfixgo/quickfix.handleInitiatorConnection GOPATH/src/github.com/quickfixgo/quickfix/connection.go:29
```

**Comment by derekparker** [comment] 2016-03-02 20:16
Hmm. How are you starting delve?

**Comment by derekparker** [comment] 2016-03-02 20:19
In the master branch of that repo, for that file:line that happens to be a end block bracket: https://github.com/quickfixgo/quickfix/blob/master/connection.go#L28. Is it possible your accidentally debugging an old binary or something?

**Comment by andradei** [comment] 2016-03-02 21:01
I'm modifying the file and running `dlv debug` on my terminal at the root of the mentioned project.

**Comment by derekparker** [comment] 2016-03-03 16:35
@andradei yes, that's correct. I'll label this as a bug and try to reproduce locally. Can you provide more details such as Go version, operating system, and the output of `dlv version`, please?

**Comment by andradei** [comment] 2016-03-03 17:46
Sure. Thank you and contributors for the amazing work with delve.

__delve__
Version: 0.11.0-alpha
Build: 6774a6c782b2f321bed46b32af45a882d55287ad

__Go__
go1.6 darwin/amd64

__OS__
OS X 10.11.3 El Capitan

**Comment by derekparker** [comment] 2017-07-26 21:38
Going to close this issue -- please reopen if you are able to produce with the latest Delve & Go versions.

**Closed by derekparker** 2017-07-26 21:38 UTC
Labels: area/proc, kind/bug, priority/P0

**Comment by amurchick** [comment] 2017-12-29 04:32
# `dlv` can not add breakpoints when I am use package(s) with `import "C"`

For example, if I am want stop on line 11 when use package with `import "C"`:
<img width="363" alt="screen shot 2017-12-29 at 11 25 27" src="https://user-images.githubusercontent.com/1515699/34429467-fd9a4d5a-ec8a-11e7-85dc-cfdc001238b0.png">

<img width="668" alt="screen shot 2017-12-29 at 11 25 50" src="https://user-images.githubusercontent.com/1515699/34429471-0d4cbdfa-ec8b-11e7-95d5-6eda40a6e535.png">


For example, if I am want stop on line 11 when not use package with `import "C"` - all ok:
<img width="374" alt="screen shot 2017-12-29 at 11 24 01" src="https://user-images.githubusercontent.com/1515699/34429454-cd186d74-ec8a-11e7-9c67-0cce5e811644.png">

<img width="572" alt="screen shot 2017-12-29 at 11 24 30" src="https://user-images.githubusercontent.com/1515699/34429459-df7e233c-ec8a-11e7-9d72-0d17735859cb.png">

**Delve**
Version: 1.0.0-rc.2
Build: $Id: 5c7676404d10d52e16be57fea744a7312b831f0c $

**GO**
go1.9.2 darwin/amd64

**OS**
macOS 10.13.2

**Code**
```
package main

import (
  "fmt"

  "github.com/karalabe/hid"
)

func main() {

  fmt.Println(hid.Supported())
  // fmt.Println(true)
}
```

**Comment by aarzilli** [comment] 2017-12-29 11:44
@amurchick your problem was likely fixed by b3246296d7bcb016542e5e86e6a01cd4b92dc1bd, you should try using a version of delve compiled from master.

**Comment by amurchick** [comment] 2017-12-30 05:06
Yes, pull and make install solved my problem. Thank you!

**Comment by jrmillerwork** [comment] 2018-06-08 09:52
I am using the most recent version of Delve and attempting to set a break at a specific line number. Initially I set a break at main.main and this works without complaint. I enter "c" and execution stops at main.main, line 150. I can experimentally try to set the same break again and it tells me that a break already exists at main.go:150. However, when I try to set a break like break main.main:150 it says Command failed could not find <path>/main.go:300 -- so it mentions a different line number and does not say it already exists. This happens immediately at the beginning of the debug session.
