### ISSUE TITLE
cgo problem? ([Could not launch program: decoding dwarf section info at offset 0x0: too short])

### ISSUE THREAD

**Issue by quarnster** [derekparker/delve#79] opened 2015-03-09 11:02 UTC
```
11:59 ~/code/go $ cat hello.go
package main

// #include <stdio.h>
// #include <stdlib.h>
// static void hack(char *str) { printf("%s", str); }
import "C"

import "unsafe"

func main() {
        cstr := C.CString("hello world!\n")
        defer C.free(unsafe.Pointer(cstr))
        C.hack(cstr)
}
11:59 ~/code/go $ go build hello.go
11:59 ~/code/go $ dlv ./hello
[Could not launch program: decoding dwarf section info at offset 0x0: too short]
11:59 ~/code/go $
dlv
Delve version 0.5.0.beta

flags:
  -v - Print version

Invoke with the path to a binary:

  dlv ./path/to/prog

or use the following commands:
  run - Build, run, and attach to program
  attach - Attach to running process

12:00 ~/code/go $ dlv -v -
flag provided but not defined: -v
Usage of dlv:
12:00 ~/code/go $ go version
go version go1.4 darwin/amd64
12:00 ~/code/go $ uname -a
Darwin Thunder 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
12:01 ~/code/go $
```

**Comment by quarnster** [comment] 2015-03-09 12:04
Appears to be related to [Go#8973](https://github.com/golang/go/issues/8973), building with `go build -ldflags="-linkmode=internal"` appears to work just fine.

Feel free to close this issue if you see nothing you'd like to fix here.

**Comment by derekparker** [comment] 2015-03-09 14:27
Thanks, this surfaced another issue of the `-v` flag not working, fixed now.

I'll keep this issue open because I can probably get a fix in to Delve to handle this until 1.5 lands.

Also, it's preferred to use `dlv run` over building yourself, simply because `run` compiles the program to be a bit more debugger friendly.

**Comment by derekparker** [comment] 2015-07-04 12:54
Going to close this issue as, according to the issue you linked to this has been patched by Russ.

**Comment by ahl** [comment] 2016-08-14 10:52
I just hit this on c3ade94b86bf9033403a493977047df8dbe5ccdd (
`could not attach to pid 39933: decoding dwarf section info at offset 0x0: too short`

Even more concerning is that `dlv` killed the process I was trying to debug.

**Comment by aarzilli** [comment] 2016-08-15 11:51
@ahl do you have steps we can follow to reproduce this or a binary to examine?

**Comment by ahl** [comment] 2016-08-16 21:07
```
package main

import "fmt"

func main() {
	for {
		fmt.Println("all work and no play makes jack a dull boy")
	}
}
```

`go run test.go` and `dlv attach $(pgrep test)` on darwin:

`could not attach to pid 68703: decoding dwarf section info at offset 0x0: too short`

Perhaps you're not supposed to use `dlv` with `go run`? Irrespective "do no harm" is job one for a debugger and my process should not end up dead in any circumstance.

This also happens on a non-golang binary. Again, the debugger should **_never_** kill target process.

**Comment by gabriel** [comment] 2016-09-01 19:39
This also happens if you use `-ldflags -s` to get macOS codesigning to work https://github.com/golang/go/issues/11887

**Comment by xsank** [comment] 2016-11-16 07:59
i use the idea to debug grafana project on windows,but meet the same problem.
> could not launch process: decoding dwarf section info at offset 0x0: too short  
after i solved this, and success use the dlv debugging, another trouble comes...  
![image](https://cloud.githubusercontent.com/assets/1661334/20339029/4bd64f30-ac15-11e6-81e9-a5f85c9dfeb5.png)
it always suspend in here from `github.com/go-stack/stack/stack.go`
here is my usage:
`C:\Users\.IntelliJIdea15\config\plugins\Go\lib\dlv\windows\dlv.exe --listen=localhost:51358 --headless=true exec "C:\Program Files (x86)\JetBrains\IntelliJ IDEA 15.0.2\jre\jre\bin\bin\Build main.exe" --
GOROOT=C:/Go
GOPATH=D:/code/mine/go
C:/Go\bin\go.exe build -ldflags -linkmode=internal -o "C:\Program Files (x86)\JetBrains\IntelliJ IDEA 15.0.2\jre\jre\bin\bin\Build main.exe" -gcflags "-N -l" github.com/grafana/grafana/pkg/cmd/grafana-server
API server listening at: 127.0.0.1:51358`
without any warnings.

**Comment by aarzilli** [comment] 2016-11-16 09:06
@xsank: this should be fixed by f6e8fb37a40312a363baec4cdde5a1ee66debf59 (see #594), update your dlv.

**Comment by xsank** [comment] 2016-11-16 09:16
@aarzilli ,is there any windows release dlv i can use or i have to build it myself?

**Comment by xsank** [comment] 2016-11-16 09:25
thank you for your help! @aarzilli

**Comment by aarzilli** [comment] 2016-11-16 09:31
@sank: you have to build it yourself.

**Closed** 2017-05-08 23:08 UTC
Labels: kind/bug, technology/cgo

**Comment by aambati** [comment] 2017-05-17 17:50
I am seeing this error in Visual Studio code Version 1.12.2 (1.12.2) on Mac:

```2017/05/17 13:41:33 server.go:73: Using API v1
2017/05/17 13:41:33 debugger.go:97: launching process with args: [./debug.test]
could not launch process: decoding dwarf section info at offset 0x0: too short
Process exiting with code: 1```

GOPATH env variable is set and dlv is installed in $GOPATH/bin directory 

launch.json looks like this:
```{
   "version": "0.2.0",
   "configurations": [
      {
         "name": "go test",
         "type": "go",
         "request": "launch",
         "mode": "test",
         "remotePath": "",
         "port": 5000,
         "host": "127.0.0.1",
         "program": "<set to directory that contains go test files>",
         "env": {},
         "args": [],
         "showLog": true
      }
   ]
}```

I have tried adding GOPATH variable to "env" configuration property in launch.json but got the same error. I am using delve version 1.0.0-rc.1

**Comment by aarzilli** [comment] 2017-05-17 18:25
Open a new issue and fill the form.
