### ISSUE TITLE
could not launch process: could not get thread count

### ISSUE THREAD

**Issue by crimsonblue02** [derekparker/delve#662] opened 2016-10-29 21:24 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
  Delve Debugger
  Version: 0.11.0-alpha
  Build: f62bf8d1e3d6cd0ebe9e327fe9bbba31356fa1e9
2. What version of Go are you using? (`go version`)?
  1.7.3
3. What operating system and processor architecture are you using?
  osx sierra
4. What did you do?
  Tried installing via homebrew and manually. 
  Ran the debugger inside IntelliJ and got this "could not launch process: could not get thread count"
  Ran the same program in the terminal with "dlv debug hello.go" and got the same error message
5. What did you expect to see?
  Delve debugging
6. What did you see instead?
  error message "could not launch process: could not get thread count"

**Comment by aarzilli** [comment] 2016-10-30 06:30
Duplicate of #645

**Closed by aarzilli** 2016-10-30 06:30 UTC
