### ISSUE TITLE
How to see code block when debugging go binary file . ? 

### ISSUE THREAD

**Issue by jacoblukose** [derekparker/delve#1021] opened 2017-11-19 12:03 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1.What version of Delve are you using (`dlv version`)?
  ` Version: 1.0.0-rc.2`
2. What version of Go are you using? (`go version`)?
 ` go1.8.3 darwin/amd64`
3. What operating system and processor architecture are you using?
`  Darwin Kernel Version 16.7.0 x86_64 OSX`
4. What did you do? 
   `dlv exec `
5. What did you expect to see?
` I was able to set breakpoints on the source code and then did go build and made the binary. But on the dlv , was unable to see the source code . Have build the executable  passing the option -gcflags='-N -l' to the compiler.`
6. What did you see instead?
Saw only lik this
```
> main.InitPlugins() ./plugins.go:4523037 (PC: 0x441ed37)
(dlv) ls
> main.InitPlugins() ./plugins.go:4523037 (PC: 0x441ed37)
(dlv) step
> sync.(*Mutex).Lock() /usr/local/go/src/sync/mutex.go:677121 (PC: 0x405ee63)
(dlv) step
> sync.(*Mutex).Lock() /usr/local/go/src/sync/mutex.go:677123 (PC: 0x405ee71)
(dlv) step
> sync.(*Mutex).Lock() /usr/local/go/src/sync/mutex.go:677127 (PC: 0x405efbe)
(dlv) step
> main.InitPlugins() ./plugins.go:4523038 (PC: 0x441ed47)
(dlv) step
> main.InitPlugins() ./plugins.go:4523040 (PC: 0x441ed75)
(dlv) ls
> main.InitPlugins() ./plugins.go:4523040 (PC: 0x441ed75)
(dlv) list
> main.InitPlugins() ./plugins.go:4523040 (PC: 0x441ed75)
(dlv)
```

How to see code block when go binary file is to be debugged using delve ?Doing the list command not showing the code block when breakpoint is hit. !

**Comment by derekparker** [comment] 2017-11-19 19:33
Where is the binary you're debugging in relation to the sources it was built from?

**Comment by jacoblukose** [comment] 2017-11-20 02:01
Binary is in the same folder as its source files.

**Comment by aarzilli** [comment] 2017-11-20 08:18
Given the line numbers I would guess it's a duplicate of #1008

**Comment by jacoblukose** [comment] 2017-11-20 09:01
The size of binary is about 14mb , no idea though.

**Comment by jacoblukose** [comment] 2017-11-20 09:05
Also its via dlv exec , and not dlv debug . Trying to debug the binary file.

**Comment by aarzilli** [comment] 2017-11-20 09:13
> Also its via dlv exec , and not dlv debug

doesn't matter.

**Comment by aarzilli** [comment] 2018-03-03 12:32
Closing, no feedback.

**Closed by aarzilli** 2018-03-03 12:32 UTC
