### ISSUE TITLE
Debugger crashes when printing vars

### ISSUE THREAD

**Issue by keshavab** [derekparker/delve#567] opened 2016-06-06 04:00 UTC
Please answer the following before submitting your issue:

$ go version go1.6 darwin/amd64
$ Delve Debugger
Version: 0.11.0-alpha
Build: v0.11.0
$ Darwin KEHP-M-X03J 14.5.0 Darwin Kernel Version 14.5.0: Thu Apr 21 20:40:54 PDT 2016; root:xnu-2782.50.3~1/RELEASE_X86_64 x86_64
4. What did you do?
vars
5. What did you expect to see?
all variables around current breakpoint.
6. What did you see instead?
Below stack trace

https://gist.github.com/keshavab/4f661150b715dd7212c0e2f314284895

**Comment by aarzilli** [comment] 2016-06-06 05:15
This looks like a duplicate of #554, it should be fixed on master already.

**Closed** 2016-06-06 05:16 UTC
