### ISSUE TITLE
Delve can not interpret correctly the expression sent by Goland to change the value of a struct member field

### ISSUE THREAD

**Issue by Gaudeamus** [derekparker/delve#1432] opened 2018-11-29 16:08 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
$ /Applications/GoLand.app/Contents/plugins/go/lib/dlv/mac/dlv version
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c

2. What version of Go are you using? (`go version`)?
$ go version
go version go1.11.1 darwin/amd64

  GoLand 2018.2.4
  Build #GO-182.5107.25, built on November 13, 2018
  Licensed to me
  Subscription is active until April 5, 2019
  JRE: 1.8.0_152-release-1248-b22 x86_64
  JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  macOS 10.13.6

3. What operating system and processor architecture are you using?
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

4. What did you do?
```
package main

type s struct {
	i int64
}
func main()  {
	i := 1
	p := &i
	s := s{i:1}
	_ = s
	println(i,p) // <-debug breakpoint is set here
}

```
I trying to update  values (e.g. 2) for all variables.

5. What did you expect to see?
Normally I was able to modify any var except strings (also not comfortable)
  
6. What did you see instead?
Set value to `i` is passed normally - it gets new value `2`
Set value to '*p' does not pass, I get error
```            
                      Error
1:1: expected operand, found 'EOF'
```
<img width="917" alt="screen shot 2018-11-29 at 18 02 25" src="https://user-images.githubusercontent.com/3287564/49234690-33712d80-f401-11e8-861c-86f06b5f29bc.png">
Set value to `s.i` does not pass, I get error

```
                           Error
expression "(*"main.s")(824633984880).i"
(main.s) can not be dereferenced
```
<img width="936" alt="screen shot 2018-11-29 at 18 02 53" src="https://user-images.githubusercontent.com/3287564/49234688-32d89700-f401-11e8-9e99-65113d15a8eb.png">

**Comment by aarzilli** [comment] 2018-12-03 14:06
I don't know why assigning to `*p` doesn't work, you should report that bug to GoLand or at least post logs here (cc @dlsniper).
The other one is a bug in delve.

**Comment by Gaudeamus** [comment] 2018-12-03 14:30
so this condition `len(v.Children) == 1` will pass  ?

**Comment by aarzilli** [comment] 2018-12-03 14:32
Yes, v is the pointer.

**Comment by Gaudeamus** [comment] 2018-12-03 14:34
ok, thanx. sorry for misunderstanding

**Closed** 2018-12-03 18:00 UTC
Labels: area/proc, kind/bug

**Comment by Gaudeamus** [comment] 2018-12-03 18:53
@aarzilli  please find log attached
[delve.log.zip](https://github.com/derekparker/delve/files/2640826/delve.log.zip)

**Comment by aarzilli** [comment] 2018-12-04 08:58
> first log:
> DEBU[0017] <- RPCServer.Set(rpc2.SetIn{"Scope":{"GoroutineID":1,"Frame":0,"DeferredCall":0},"Symbol":"","Value":"2"})  layer=rpc

It's not sending anything in Symbol.

> second log:
> DEBU[0027] <- RPCServer.Set(rpc2.SetIn{"Scope":{"GoroutineID":1,"Frame":0,"DeferredCall":0},"Symbol":"*(*\"main.s\")(824633984880).i","Value":"2"})  layer=rpc

GoLand is sending `*(*"main.s")(824633984880).i` which is parsed as `*((*"main.s")(824633984880).i)` for which the error we are returning `expression "(*\"main.s\")(824633984880).i" (int64) can not be dereferenced` is correct.

**Comment by dlsniper** [comment] 2018-12-04 10:34
@aarzilli thank you for the patch. I can confirm that the rest of the problem is in GoLand side.
