### ISSUE TITLE
[OSX 10.10.3] Can't seem to be able to debug a program or attach to an existing one

### ISSUE THREAD

**Issue by keltia** [derekparker/delve#159] opened 2015-06-30 12:01 UTC
Running a process then attaching:

    296 [13:56] roberto@roberto-aw> sudo dlv attach 59077
    Password:
    could not attach to pid 59077: could not get thread count
    [Hope I was of service hunting your bug!]

The process to be attached is:

    574 [13:55] roberto@roberto-aw:src/flightaware-go> ./bin/fa-export
    2015/06/30 13:55:55 Connecting to foxtrot.hou.flightaware.com:1501 with TLS
    2015/06/30 13:55:56 TLS negociation done.
    2015/06/30 13:55:56 Flightaware init done.
    2015/06/30 13:55:56 Waiting for data…
    2015/06/30 13:55:56 Loop
    [1]    59077 killed     ./bin/fa-export

trying to run the process through dlv:

    572 [13:54] roberto@roberto-aw:src/flightaware-go> ll !$
    ll bin/fa-export
    -rwxr-xr-x  1 roberto  staff  5551876 Jun 30 12:06 bin/fa-export*
    573 [13:54] roberto@roberto-aw:src/flightaware-go> dlv ./bin/fa-export
    could not launch process: could not fork/exec
    [Hope I was of service hunting your bug!]

Code is at https://github.com/keltia/flightaware-go/

**Comment by derekparker** [comment] 2015-06-30 14:33
What OS are you running?

I was able to build and run through Delve with the following commands:

```
derekparker at flightaware-go(master) make
go build -v -o bin/fa-export fa-export/fa-export.go fa-export/cli.go
gopkg.in/yaml.v2
_/Users/derekparker/go/src/github.com/keltia/flightaware-go/config
_/Users/derekparker/go/src/github.com/keltia/flightaware-go/flightaware
command-line-arguments
derekparker at flightaware-go(master+) dlv bin/fa-export
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x2300 for main.main /Users/derekparker/go/src/github.com/keltia/flightaware-go/fa-export/fa-export.go:36
(dlv) c
current loc: main.main /Users/derekparker/go/src/github.com/keltia/flightaware-go/fa-export/fa-export.go:36
   31:                  log.Fatalf("Error writing %d bytes: %v", nb, err)
   32:          }
   33:  }
   34:
   35:  // Starts here.
=> 36:  func main() {
   37:          // Handle SIGINT
   38:          go func() {
   39:              sigint := make(chan os.Signal, 3)
   40:              signal.Notify(sigint, os.Interrupt)
   41:              <-sigint

(dlv) Would you like to kill the process? [Y/n]
[Hope I was of service hunting your bug!]
```

**Comment by derekparker** [comment] 2015-06-30 14:41
@keltia I imagine some flavor of FreeBSD?

**Comment by keltia** [comment] 2015-06-30 14:44
Nope, unless you consider OS X to be one (which it is in a way ok).  I'm running OS X 10.10.3 as indicated in the subject line :)

**Comment by derekparker** [comment] 2015-06-30 14:50
@keltia ah, sorry... I'm still waiting on coffee to kick in ;).

I'm running the same system and I was able to pass along the path to Delve. I can attempt attaching to a running process and see if that makes any difference.

**Comment by keltia** [comment] 2015-06-30 14:54
`could not launch process: could not fork/exec` seems to indicate some kind of resource shortage but the rest of the system does work.

**Comment by derekparker** [comment] 2015-06-30 14:54
@keltia have you gone through the process of code signing the `dlv` binary?

**Comment by keltia** [comment] 2015-06-30 15:04
Yes, created a fake self-signed root cert and signed.  I could also have used my own certificate but didn't thought of that.

**Comment by derekparker** [comment] 2015-07-01 02:00
I am unable to reproduce this issue, I was able to attach to the binary by passing along the path.

Have you been able to use Delve successfully on your machine before? Could you try `dlv run` on an extremely simple test program and verify that it works?

If it does not work with a simple test program than I honestly suspect it is an issue with the cert.

**Comment by derekparker** [comment] 2015-07-04 13:01
Closing as related to #134.

**Closed by derekparker** 2015-07-04 13:01 UTC
Labels: bug

**Comment by ObviousDesign** [comment] 2015-11-13 13:07
Thanks for writing this great piece of software! Just compiled it on OSX 10.11 following all the required steps. I have the same issue when launching a debug session: 

$ dlv debug main.go
could not launch process: could not fork/exec

The way I was able to resolve this is by running the command as sudo.

$ sudo dlv debug main.go
Password:
Type 'help' for list of commands.
(dlv)

**Comment by derekparker** [comment] 2015-11-13 18:19
@ObviousDesign thanks for checking it out! The `debug` subcommand actually does not take an argument, it expects to be run where you would run `go build` without any args. Secondly, since sudo worked for you, it seems there is an issue with how the `dlv` binary was codesigned. For sanity checks, did you make sure you killed the `taskgated` process? Also, the output of `make install` could be useful here.

**Comment by ObviousDesign** [comment] 2015-11-16 07:51
Hi @derekparker, I was not able to kill the `taskgated` process before compiling first time. Now recompiled after a fresh restart and I am now able to run `dlv` without `sudo`. Thank you for your support. Jeroen

**Comment by newhook** [comment] 2015-11-28 17:53
I cannot get delve to work on OSX 10.11. I followed the directions but get the cannot fork error. The binary appears to be codesigned correctly?

```
➜  delve git:(master) ✗ codesign -v ~/go/bin/dlv
➜  delve git:(master) ✗ echo $?
0
```

**Comment by loganjspears** [comment] 2016-03-04 15:21
I had the same issue and it was related to **taskgated**.  I just restarted and everything worked.

**Comment by jkowalski** [comment] 2016-03-06 02:01
FWIF I had similar issue today:

"sudo dlv exec ./blah" worked fine, but "dlv exec ./blah" would print the dreaded "could not launch process: could not fork/exec".

I double checked that the certificate was configured properly and that dlv was properly signed. Restarting taskgated did not help in my case. 

What helped was - surprisingly - starting XCode. Apparently the first time it starts, it installs some debugging support tools, which seems to allow dlv to run as regular user.

**Comment by helinwang** [comment] 2016-03-07 04:13
Make sure each time you try the code sign, run `sudo pkill taskgated` first.

**Comment by MariMurotani** [comment] 2016-03-19 15:37
I have same problem that I get error below except root user.
could not launch process: could not fork/exec
I killed taskgated just before make, but taskgated restarts after make process.

OS: OSX Yosemite 10.10.4
Darwin Kernel Version 14.4.0
