### ISSUE TITLE
Any plans to support Go plugins with delve ?

### ISSUE THREAD

**Issue by fsunaval** [derekparker/delve#1114] opened 2018-02-02 21:42 UTC
I know that delve does not currently support plugins.

Are there any plans to support plugins or any technical challenges that make this difficult to implement?

**Comment by dlsniper** [comment] 2018-02-03 00:34
Duplicate of #865

**Comment by dlsniper** [comment] 2018-02-03 00:37
Also you've opened #1099 which got closed as duplicate as well.
Clearly this is important for you, so if you want, why don't you try and contribute the issue yourself to delve? Spamming the developers like this will not help move the issue any further.

**Comment by aarzilli** [comment] 2018-02-05 16:04
Logically support for PIEs would have to be implemented first, I don't foresee any substantial technical challenges but you never know.

Closing as duplicate.

**Closed by aarzilli** 2018-02-05 16:04 UTC
