### ISSUE TITLE
OS X: could not launch process: could not get thread count

### ISSUE THREAD

**Issue by r258833095** [derekparker/delve#652] opened 2016-10-13 04:29 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 0.11.0-alpha
Build: 46803551b888c017e22bef94d6bf223a9eb704a3

2. What version of Go are you using? (`go version`)?
go version go1.7.1 darwin/amd64

3. What operating system and processor architecture are you using?
OS X 10.12.1 Beta (16B2338c)

4. What did you do?
Tried to debug my app from with in Visual Studio Code

5. What did you expect to see?
The debug console

6. What did you see instead?
2016/10/13 12:21:25 server.go:71: Using API v1
2016/10/13 12:21:25 debugger.go:61: launching process with args: [./debug]
could not launch process: could not get thread count

**Comment by aarzilli** [comment] 2016-10-13 10:28
Duplicate of #645

**Closed by aarzilli** 2016-10-13 10:28 UTC
