### ISSUE TITLE
Problems when following a non-main goroutine with 'next' command: Delve doesn't detect the end of the program

### ISSUE THREAD

**Issue by schomatis** [derekparker/delve#1101] opened 2018-01-27 13:50 UTC
Playing with a basic [goroutine example](https://gobyexample.com/goroutines) to add it to the getting started guide I came across a series of panics and hangs (that I believe are all related) when switching to a non-`main` goroutine and following it with `next`, because (I'm guessing) Delve at some point misses the end of the program and pointers like `(*Thread)` in the server or `DebuggerState.CurrentThread` in the client are `nil`. I'll be looking deeper into this issue but I document it here to get some feedback about it.

The problem, as it deals with threads and goroutines, is not completely deterministic but comes up often enough (at least in my machine) that after a couple of tries it will manifest itself (in different ways). In it most basic form the test code is an empty main function that spawns a goroutine (also empty) and waits for it (the `sync.Wait` was added to the cited example):

```go
package main

import (
    "sync"
)

var wg sync.WaitGroup

func f(from string) {
    defer wg.Done()
    return
}

func main() {
    wg.Add(1)
    go f("goroutine")
    wg.Wait()
}
```

Building the binary

```
$ dlv debug --output debug_binary
```

and running the following CLI commands that break inside the function executed by the goroutine (with an implicit goroutine switch)

```
r
b main.main
c
b f
c
n # repeated three times to exit f() goroutine
n
n
```

leaves it inside the created goroutine

```
     8:	
=>   9:	func f(from string) {
    10:	    defer wg.Done()
    11:	    return
    12:	}
    13:	
    14:	func main() {
(dlv) goroutines
[4 goroutines]
  Goroutine 1 - User: /usr/local/go/src/runtime/sema.go:56 sync.runtime_Semacquire (0x4350b9)
  Goroutine 2 - User: /usr/local/go/src/runtime/proc.go:288 runtime.gopark (0x427b2d)
  Goroutine 17 - User: /usr/local/go/src/runtime/proc.go:288 runtime.gopark (0x427b2d)
* Goroutine 18 - User: ./main.go:9 main.f (0x455f1f) (thread 21588)
(dlv) 
```

From this point, following the execution with the `next` command sometimes ends correctly with the process termination, but in other cases it results in panics or hangs. Alternatively, using the command `continue` always ends correctly without issues.

Problem 1: panic in the terminal client.

```
No current thread available
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7be5fb]

goroutine 1 [running]:
github.com/derekparker/delve/pkg/terminal.continueUntilCompleteNext(0xc420061e60, 0xc4204362a0, 0xaecfb2, 0x4, 0x0, 0x0)
	/home/user/go/src/github.com/derekparker/delve/pkg/terminal/command.go:749 +0x20b
github.com/derekparker/delve/pkg/terminal.next(0xc420061e60, 0x0, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x2, 0x0)
	/home/user/go/src/github.com/derekparker/delve/pkg/terminal/command.go:823 +0x116
github.com/derekparker/delve/pkg/terminal.(*Commands).CallWithContext(0xc420171d40, 0xc420293bec, 0x0, 0xc420061e60, 0x0, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0)
	/home/user/go/src/github.com/derekparker/delve/pkg/terminal/command.go:348 +0x12a
github.com/derekparker/delve/pkg/terminal.(*Commands).Call(0xc420171d40, 0xc420293bec, 0x0, 0xc420061e60, 0x0, 0x0)
	/home/user/go/src/github.com/derekparker/delve/pkg/terminal/command.go:353 +0x71
github.com/derekparker/delve/pkg/terminal.(*Term).Run(0xc420061e60, 0x0, 0x0, 0x0)
	/home/user/go/src/github.com/derekparker/delve/pkg/terminal/terminal.go:132 +0x33c
github.com/derekparker/delve/cmd/dlv/cmds.execute(0x0, 0xc42014e3b0, 0x1, 0x1, 0xc420156240, 0x0, 0x0, 0x1, 0x0)
	/home/user/go/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:537 +0x8e3
github.com/derekparker/delve/cmd/dlv/cmds.debugCmd.func1(0xc420172900, 0xc42014c480, 0x0, 0x2, 0x0)
	/home/user/go/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:300 +0x405
github.com/derekparker/delve/cmd/dlv/cmds.debugCmd(0xc420172900, 0xc42014c480, 0x0, 0x2)
	/home/user/go/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:301 +0x49
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).execute(0xc420172900, 0xc42014c300, 0x2, 0x2, 0x0, 0x0)
	/home/user/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:647 +0xa4e
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420172240, 0xc420172900, 0x0, 0x0)
	/home/user/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:733 +0x68c
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420172240, 0x0, 0x0)
	/home/user/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:692 +0x4f
main.main()
	/home/user/go/src/github.com/derekparker/delve/cmd/dlv/main.go:18 +0x91

```

Problem 2: panic in the debugger server when restarting what appeared to be a correct end in the execution

```
(dlv) r
Command failed: Internal debugger error: runtime error: invalid memory address or nil pointer dereference
runtime.call32 (0x45ceba)
	/usr/local/go/src/runtime/asm_amd64.s:509
runtime.gopanic (0x42f541)
	/usr/local/go/src/runtime/panic.go:491
runtime.panicmem (0x42e41d)
	/usr/local/go/src/runtime/panic.go:63
runtime.sigpanic (0x44649b)
	/usr/local/go/src/runtime/signal_unix.go:367
github.com/derekparker/delve/pkg/proc/native.(*Thread).stopped (0x797392)
	/home/user/go/src/github.com/derekparker/delve/pkg/proc/native/threads_linux.go:34
github.com/derekparker/delve/pkg/proc/native.(*Thread).Stopped (0x796a8a)
	/home/user/go/src/github.com/derekparker/delve/pkg/proc/native/threads.go:120
github.com/derekparker/delve/pkg/proc/native.(*Process).Kill (0x7916fd)
	/home/user/go/src/github.com/derekparker/delve/pkg/proc/native/proc_linux.go:106
github.com/derekparker/delve/pkg/proc/native.(*Process).Detach (0x78ee2e)
	/home/user/go/src/github.com/derekparker/delve/pkg/proc/native/proc.go:82
github.com/derekparker/delve/service/debugger.(*Debugger).detach (0x79a61b)
	/home/user/go/src/github.com/derekparker/delve/service/debugger/debugger.go:177
github.com/derekparker/delve/service/debugger.(*Debugger).Restart (0x79a78d)
	/home/user/go/src/github.com/derekparker/delve/service/debugger/debugger.go:203
github.com/derekparker/delve/service/rpc2.(*RPCServer).Restart (0x977f87)
	/home/user/go/src/github.com/derekparker/delve/service/rpc2/server.go:83
runtime.call128 (0x45cfd1)
	/usr/local/go/src/runtime/asm_amd64.s:511
reflect.Value.call (0x4e21b5)
	/usr/local/go/src/reflect/value.go:434
reflect.Value.Call (0x4e1366)
	/usr/local/go/src/reflect/value.go:302
github.com/derekparker/delve/service/rpccommon.(*ServerImpl).serveJSONCodec.func1 (0x98095d)
	/home/user/go/src/github.com/derekparker/delve/service/rpccommon/server.go:299
github.com/derekparker/delve/service/rpccommon.(*ServerImpl).serveJSONCodec (0x97f52d)
	/home/user/go/src/github.com/derekparker/delve/service/rpccommon/server.go:301
runtime.goexit (0x45f6e0)
	/usr/local/go/src/runtime/asm_amd64.s:2337
```

Problem 3: Delve hangs with a zombie process.

```
$ command ps aux -T | grep debug_bin
user     15052 15052  0.0  0.0      0     0 pts/18   Zl   08:58   0:00 [debug_binary] <defunct>
user     15052 15053  0.0  0.0      0     0 pts/18   Zl   08:58   0:00 [debug_binary] <defunct>
user     15052 15054  0.0  0.0      0     0 pts/18   Zl   08:58   0:00 [debug_binary] <defunct>
```

Removing the `Wait` call in `main`, although it makes it less probable that Delve will hit the breakpoint inside the goroutine (because `main` ends before that), when it does, it always (or very likely) causes one of the above described problems because (I'm guessing again) Delve is not detecting the end of the `main` goroutine while stepping through the (now dead) non-`main` goroutine. (To increase the probability of hitting the breakpoint the removed `Println` statement from the cited example should be added again to the function executed by the goroutine.)

Development environment:

```
go version go1.9.2 linux/amd64
Delve Debugger
Version: 1.0.0-rc.2
Build: 74d330a013a5412649aaa069d932b93889c2dbd2
```

**Comment by dlsniper** [comment] 2018-01-27 14:03
This is a duplicate of #1090 which is solved in #1098

**Comment by schomatis** [comment] 2018-01-27 14:13
Oh, too bad I missed it, thanks @dlsniper, when that is merged I'll retest this and close it.

**Comment by derekparker** [comment] 2018-01-27 19:24
Fixed via https://github.com/derekparker/delve/pull/1098 which is now merged.

**Comment by schomatis** [comment] 2018-01-27 20:24
@derekparker I've retested this and problems 2 and 3 persist.

Their manifestation is not deterministic and the CLI commands need to be executed a couple of times to reproduce them, at least in my setup (they can be pasted all together in Delve's terminal repeatedly).

```
Delve Debugger
Version: 1.0.0-rc.2
Build: 045763ef04ac0cdfeb646d08fbce982119fa51a2
```

**Comment by derekparker** [comment] 2018-01-28 09:39
@schomatis thanks for re-testing and reporting back.

**Comment by schomatis** [comment] 2018-01-29 03:02
Problem 3 seems to be caused by calls to [`waitFast`](https://github.com/derekparker/delve/blob/045763ef04ac0cdfeb646d08fbce982119fa51a2/pkg/proc/native/proc_linux.go#L331) in [`threads_linux.go`](https://github.com/derekparker/delve/blob/045763ef04ac0cdfeb646d08fbce982119fa51a2/pkg/proc/native/threads_linux.go#L54) and [`proc_linux.go`](https://github.com/derekparker/delve/blob/045763ef04ac0cdfeb646d08fbce982119fa51a2/pkg/proc/native/proc_linux.go#L140), changing those calls to [`wait`](https://github.com/derekparker/delve/blob/045763ef04ac0cdfeb646d08fbce982119fa51a2/pkg/proc/native/proc_linux.go#L338) seems to fix this.

For a simple PoC one can debug an empty `main` function and stop before the [`exit_group`](https://linux.die.net/man/2/exit_group) system call (inside runtime code)

```
(dlv) b sys_linux_amd64.s:16
Breakpoint 1 set at 0x450749 for runtime.exit() /usr/local/go/src/runtime/sys_linux_amd64.s:16
(dlv) c
> runtime.exit() /usr/local/go/src/runtime/sys_linux_amd64.s:16 (hits goroutine(1):1 total:1) (PC: 0x450749)
Warning: debugging optimized function
    11:	#include "textflag.h"
    12:	
    13:	TEXT runtime·exit(SB),NOSPLIT,$0-4
    14:		MOVL	code+0(FP), DI
    15:		MOVL	$231, AX	// exitgroup - force all os threads to exit
=>  16:		SYSCALL
    17:		RET
    18:	
    19:	TEXT runtime·exit1(SB),NOSPLIT,$0-4
    20:		MOVL	code+0(FP), DI
    21:		MOVL	$60, AX	// exit - exit the current os thread
(dlv) 
```

and try to continue execution either with `continue`. `next`, `step-instruction`, etc.

Making the changes to `wait` leaves problem 2 with a more deterministic manifestation.

**Comment by aarzilli** [comment] 2018-01-29 09:11
@schomatis I'm testing a fix, it's a race condition between delve's continue and death of the target process, combined with the problematic behavior of linux's waitpid when it's called on the thread group leader.

**Closed** 2018-03-06 17:06 UTC
Labels: area/proc/native, kind/bug, os/linux
