### ISSUE TITLE
dlv panic when attaching dockerd in centos

### ISSUE THREAD

**Issue by chengyli** [derekparker/delve#939] opened 2017-08-03 14:55 UTC
I tried to run dlv to attach dockerd, but dlv itself panic.

```
Delve Debugger
Version: 1.0.0-rc.1
Build: 7214ffe20ed70216ab8c8b67efcf4ae62d4a1812
```
```
$ go version
go version go1.7.4 linux/amd64
```
```
$ cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
```
```
$ docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64
```

```
$ ps -ef | grep dockerd
root     18605     1  0 Aug02 ?        00:00:48 /usr/bin/dockerd-current --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current --default-runtime=docker-runc --exec-opt native.cgroupdriver=systemd --userland-proxy-path=/usr/libexec/docker/docker-proxy-current --selinux-enabled --log-driver=journald --signature-verification=false

$ sudo ./dlv attach 18605
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5e2b46]

goroutine 1 [running]:
panic(0x92d300, 0xc4200120e0)
	/usr/lib/golang/src/runtime/panic.go:500 +0x1a1
debug/gosym.(*Table).LookupFunc(0x0, 0x9c6ca7, 0x12, 0xc42004b7c8)
	/usr/lib/golang/src/debug/gosym/symtab.go:564 +0x26
github.com/derekparker/delve/pkg/proc.FindFunctionLocation(0xc2b240, 0xc4201529c0, 0x9c6ca7, 0x12, 0xc420012c01, 0x0, 0x48ad, 0x0, 0x0)
	/home/centos/GO/src/github.com/derekparker/delve/pkg/proc/proc.go:54 +0x6c
github.com/derekparker/delve/pkg/proc/native.initializeDebugProcess(0xc4201529c0, 0x0, 0x0, 0x48ad, 0xc420164768, 0x0)
	/home/centos/GO/src/github.com/derekparker/delve/pkg/proc/native/proc.go:404 +0xf6
github.com/derekparker/delve/pkg/proc/native.Attach(0x48ad, 0x7, 0x9be4aa, 0x7)
	/home/centos/GO/src/github.com/derekparker/delve/pkg/proc/native/proc_linux.go:93 +0x195
github.com/derekparker/delve/service/debugger.(*Debugger).Attach(0xc420162700, 0x48ad, 0x0, 0x0, 0x1, 0xc41fff50c3, 0x0, 0x48)
	/home/centos/GO/src/github.com/derekparker/delve/service/debugger/debugger.go:150 +0x15b
github.com/derekparker/delve/service/debugger.New(0xc42015e780, 0xc42015e780, 0xc42004ba20, 0x40fc28)
	/home/centos/GO/src/github.com/derekparker/delve/service/debugger/debugger.go:74 +0x16c
github.com/derekparker/delve/service/rpccommon.(*ServerImpl).Run(0xc42015e730, 0xc420178400, 0xc42015e730)
	/home/centos/GO/src/github.com/derekparker/delve/service/rpccommon/server.go:119 +0x187
github.com/derekparker/delve/cmd/dlv/cmds.execute(0x48ad, 0xc4201644c0, 0x0, 0x0, 0xc420162140, 0x0, 0x0, 0x3, 0x0)
	/home/centos/GO/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:484 +0x288
github.com/derekparker/delve/cmd/dlv/cmds.attachCmd(0xc42018a480, 0xc4201644c0, 0x1, 0x1)
	/home/centos/GO/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:401 +0xe1
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).execute(0xc42018a480, 0xc420164470, 0x1, 0x1, 0xc42018a480, 0xc420164470)
	/home/centos/GO/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:647 +0x446
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42018a240, 0xc42018a900, 0xc42018a6c0, 0xc42018a480)
	/home/centos/GO/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:733 +0x367
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42018a240, 0xc42018a240, 0xc4200001a0)
	/home/centos/GO/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:692 +0x2b
main.main()
	/home/centos/GO/src/github.com/derekparker/delve/cmd/dlv/main.go:15 +0x5f
```

**Comment by aarzilli** [comment] 2017-08-15 10:18
Can you run `objdump -h /usr/bin/dockerd-current` and post the output?

**Comment by ignatov** [comment] 2017-10-13 14:12
The same is on Mac https://youtrack.jetbrains.com/v2/issue/GO-4299

**Comment by aarzilli** [comment] 2017-10-13 14:21
My guess is that this is caused by stripped binaries.

**Comment by aarzilli** [comment] 2018-03-03 12:35
Closing, no feedback.

**Closed by aarzilli** 2018-03-03 12:35 UTC
Labels: area/proc, kind/bug
