### ISSUE TITLE
The output of "goroutines" command is different with "runtime.NumGoroutine()".

### ISSUE THREAD

**Issue by NanXiao** [derekparker/delve#553] opened 2016-05-27 03:02 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
0.11.0-alpha.

2. What version of Go are you using? (`go version`)?
go1.6.2.

3. What operating system and processor architecture are you using?
linux/amd64.

4. Issue:
The program code is like this:
```
package main

import (
        "fmt"
        "runtime"
)

func main() {
        fmt.Println(runtime.NumGoroutine())
}
```
When using `Delve` to debug it, the `goroutines` command shows there are `4` goroutines, but actually the output of `fmt.Println(runtime.NumGoroutine())` is only `1`:  
```
(dlv) b main.main
Breakpoint 1 set at 0x401013 for main.main() ./goroutine.go:8
(dlv) c
> main.main() ./goroutine.go:8 (hits goroutine(1):1 total:1) (PC: 0x401013)
     3: import (
     4:         "fmt"
     5:         "runtime"
     6: )
     7:
=>   8: func main() {
     9:         fmt.Println(runtime.NumGoroutine())
    10: }
(dlv) n
> main.main() ./goroutine.go:9 (PC: 0x401017)
     4:         "fmt"
     5:         "runtime"
     6: )
     7:
     8: func main() {
=>   9:         fmt.Println(runtime.NumGoroutine())
    10: }
(dlv) goroutines
[4 goroutines]
* Goroutine 1 - User: ./goroutine.go:9 main.main (0x401017)
  Goroutine 2 - User: /usr/local/go/src/runtime/proc.go:263 runtime.gopark (0x429f43)
  Goroutine 3 - User: /usr/local/go/src/runtime/proc.go:263 runtime.gopark (0x429f43)
  Goroutine 4 - User: /usr/local/go/src/runtime/proc.go:263 runtime.gopark (0x429f43)
(dlv) n
1
> main.main() ./goroutine.go:10 (PC: 0x4010d9)
     5:         "runtime"
     6: )
     7:
     8: func main() {
     9:         fmt.Println(runtime.NumGoroutine())
=>  10: }
(dlv) goroutines
[4 goroutines]
* Goroutine 1 - User: ./goroutine.go:10 main.main (0x4010d9)
  Goroutine 2 - User: /usr/local/go/src/runtime/proc.go:263 runtime.gopark (0x429f43)
  Goroutine 3 - User: /usr/local/go/src/runtime/proc.go:263 runtime.gopark (0x429f43)
  Goroutine 4 - User: /usr/local/go/src/runtime/proc.go:263 runtime.gopark (0x429f43)
```
How to understand the difference? Is it a bug?

**Comment by NanXiao** [comment] 2016-05-28 02:55
@aarzilli I see you tagged this issue as an enhancement. Isn't it a bug? How to understand it? Thanks!

**Comment by aarzilli** [comment] 2016-05-28 04:37
We are currently reporting the contents of runtime.allg, NumGoroutine probably filters it somehow, I need to look into it.

**Comment by aarzilli** [comment] 2016-05-29 09:14
I've looked into this.

Runtime hides from the user all goroutines matching this boolean expression:

```
// isSystemGoroutine reports whether the goroutine g must be omitted in
// stack dumps and deadlock detector.
func isSystemGoroutine(gp *g) bool {
	pc := gp.startpc
	return pc == runfinqPC && !fingRunning ||
		pc == bgsweepPC ||
		pc == forcegchelperPC ||
		pc == timerprocPC ||
		pc == gcBgMarkWorkerPC
}
```

This function is found at $GOROOT/src/runtime/traceback.go:735 for 1.6.2. If we look at the three mystery goroutines we see this:

```
(dlv) goroutines
[4 goroutines]
* Goroutine 1 - User: ./goroutines.go:9 main.main (0x401017) (thread 28959)
  Goroutine 2 - User: /usr/local/go/src/runtime/proc.go:263 runtime.gopark (0x429f43)
  Goroutine 3 - User: /usr/local/go/src/runtime/proc.go:263 runtime.gopark (0x429f43)
  Goroutine 4 - User: /usr/local/go/src/runtime/proc.go:263 runtime.gopark (0x429f43)
(dlv) goroutine 2 stack
0  0x0000000000429f43 in runtime.gopark
   at /usr/local/go/src/runtime/proc.go:263
1  0x0000000000429fc3 in runtime.goparkunlock
   at /usr/local/go/src/runtime/proc.go:268
2  0x0000000000429d15 in runtime.forcegchelper
   at /usr/local/go/src/runtime/proc.go:229
3  0x00000000004558c0 in runtime.goexit
   at /usr/local/go/src/runtime/asm_amd64.s:1998
(dlv) goroutine 3 stack
0  0x0000000000429f43 in runtime.gopark
   at /usr/local/go/src/runtime/proc.go:263
1  0x0000000000429fc3 in runtime.goparkunlock
   at /usr/local/go/src/runtime/proc.go:268
2  0x000000000041bfae in runtime.bgsweep
   at /usr/local/go/src/runtime/mgcsweep.go:63
3  0x00000000004558c0 in runtime.goexit
   at /usr/local/go/src/runtime/asm_amd64.s:1998
(dlv) goroutine 4 stack
0  0x0000000000429f43 in runtime.gopark
   at /usr/local/go/src/runtime/proc.go:263
1  0x0000000000429fc3 in runtime.goparkunlock
   at /usr/local/go/src/runtime/proc.go:268
2  0x0000000000413de7 in runtime.runfinq
   at /usr/local/go/src/runtime/mfinal.go:158
3  0x00000000004558c0 in runtime.goexit
   at /usr/local/go/src/runtime/asm_amd64.s:1998
(dlv) 
```

Which means that the three mystery goroutines are forcegchelper, bgsweep and runfinq. Hiding them in delve is easy enough (we can also check StartPC) but I lean against doing it. Showing those extra goroutines doesn't hurt anyone and I feel that if we did hide them then we should also add an option to show them.

**Comment by NanXiao** [comment] 2016-05-29 11:42
@aarzilli Got it! Thanks very much for your detailed explanation and time!

**Comment by derekparker** [comment] 2016-05-29 19:34
Closing as not a bug.

**Closed by derekparker** 2016-05-29 19:34 UTC
Labels: area/proc, kind/enhancement
