### ISSUE TITLE
Readily reproducible delve crash: "panic: runtime error: makeslice: len out of range"

### ISSUE THREAD

**Issue by ryho** [derekparker/delve#630] opened 2016-09-09 17:44 UTC
1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 0.11.0-alpha
Build: v0.11.0
```
1. What version of Go are you using? (`go version`)?  
   `go version go1.7.1 darwin/amd64`
2. What operating system and processor architecture are you using?  
   OSX 10.11.6, 64 bit x86
3. What did you do?  
   I'm running Delve with Visual Studio Code, here is my launch.json:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "TestFoo",
            "type": "go",
            "request": "launch",
            "mode": "test",
            "program": "${workspaceRoot}/foo/bar",
            "env": {},
            "args": ["-test.run","^TestFoo$"],
            "showLog": true
        }
    ]
}
```

Method 1: I put a breakpoint inside the test, click run, and click step in.
Method 2: I put a breakpoint inside the function, click run.
5. What did you expect to see?  
In both cases, I expect it to pause inside the function.
6. What did you see instead?  
Delve crashes when it gets inside the function with this output:  
https://gist.github.com/ryho/36163b8fcfb6e260ad7214a36a8df374
It doesn't happen in every function, only some. And it seems to crash every time for the functions that cause it to crash. I'm working in a decently large project.

**Comment by aarzilli** [comment] 2016-09-09 17:47
Looks like this bug https://github.com/derekparker/delve/issues/622 if it is it's already fixed on master, see if you can reproduce with delve compiled from master.

**Closed** 2017-04-27 01:51 UTC
