### ISSUE TITLE
Run/Debug sever without client connection

### ISSUE THREAD

**Issue by chucktesejme** [derekparker/delve#1152] opened 2018-03-13 12:36 UTC
We want to use Delve for Go server debugging in docker container so we build go by: 

`go build -i "-ldflags=-linkmode internal" -o /tmp/go_build -gcflags "-N -l" /home/develop/main.go`

and when we run it:

`dlv --listen=localhost:5005 --headless=false --api-version=2 --backend=default exec  /tmp/go_build`

server outputs:
API server listening at: 127.0.0.1:5005

but problem is that Go server waiting for client connection, if client won't connect server will not run.

Is it possible to run server in debug mode without client connection ? because we won't want debug server in every case ? 

Something like Java debugger has `suspend=n` option. Means that server will run and serve requests and debug client can connect anytime.

**Comment by aarzilli** [comment] 2018-03-16 13:41
Duplicate of #952

**Closed** 2018-03-21 20:23 UTC
