### ISSUE TITLE
It cann't install in RaspberryPi.

### ISSUE THREAD

**Issue by qinains** [derekparker/delve#1193] opened 2018-04-22 09:38 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.
https://github.com/derekparker/delve/tree/35622fd6676bf17988b5cb6642a53b65dd1d5998

1. What version of Delve are you using (`dlv version`)?
origin/master

2. What version of Go are you using? (`go version`)?
go version go1.7.4 linux/arm

3. What operating system and processor architecture are you using?
linux/arm

4. What did you do?
go get github.com/derekparker/delve/cmd/dlv

5. What did you expect to see?
Install success.

6. What did you see instead?
go get github.com/derekparker/delve/cmd/dlv
# github.com/derekparker/delve/pkg/proc
pkg/proc/disasm.go:11: undefined: ArchInst

**Comment by aarzilli** [comment] 2018-04-22 10:28
Duplicate of #118

**Closed by aarzilli** 2018-04-22 10:28 UTC
