### ISSUE TITLE
stepout should not be able to crash the server

### ISSUE THREAD

**Issue by gertcuykens** [derekparker/delve#1253] opened 2018-06-29 09:18 UTC
Delve Debugger OSX
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533
go version go1.10.2 darwin/amd64
```
package main

import (
	"fmt"
)

func main() {
	x := 1
	fmt.Println("Hello 1", x)
	fmt.Println("Hello 2", x)
}
```
When doing stepout immediately as frist command the service crashes
```
$ dlv debug
Type 'help' for list of commands.
(dlv) stepout
Command failed: invalid error <nil>
(dlv) r
Command failed: connection is shut down
(dlv)
```
It should just run the program like any other command instead

**Comment by dlsniper** [comment] 2018-06-29 09:40
Here I would expect to kill the program instead of running it.

**Comment by aarzilli** [comment] 2018-07-02 09:39
Duplicate of #1251

**Closed by aarzilli** 2018-07-02 09:39 UTC
