### ISSUE TITLE
VSCODE can not debug

### ISSUE THREAD

**Issue by a57571735** [derekparker/delve#678] opened 2016-11-28 13:33 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
$ dlv version
Delve Debugger
Version: 0.11.0-alpha
Build: 6bff4d19706b46b7bd350212048e4a140caad271
2. What version of Go are you using? (`go version`)?
$ go version
go version go1.7.3 darwin/amd64
3. What operating system and processor architecture are you using?
macOS Sierra 10.12.1
4. What did you do?
install delve and use vscode debug
5. What did you expect to see?

6. What did you see instead?

$ brew install go-delve/delve/delve
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Installing delve from go-delve/homebrew-delve
==> Installing dependencies for go-delve/delve/delve: go
==> Installing go-delve/delve/delve dependency: go
==> Downloading https://storage.googleapis.com/golang/go1.5.1.src.tar.gz
Already downloaded: /Library/Caches/Homebrew/go-1.5.1.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10
Already downloaded: /Library/Caches/Homebrew/go--gobootstrap-10.8.tar.gz
==> ./make.bash --no-clean
==> ./make.bash --no-clean
goroutine 5 [syscall]:
os/signal.loop()
	/private/tmp/go20161128-3918-1ci0m2j/go/gobootstrap/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/private/tmp/go20161128-3918-1ci0m2j/go/gobootstrap/src/os/signal/signal_unix.go:27 +0x35

READ THIS: https://git.io/brew-troubleshooting

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /usr/local/Library/Homebrew/utils.rb:436:in `open'
	from /usr/local/Library/Homebrew/utils.rb:466:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:498:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:209:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:205:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:248:in `dump'
	from /usr/local/Library/brew.rb:154:in `rescue in <main>'
	from /usr/local/Library/brew.rb:67:in `<main>'

vscode console

2016/11/28 21:24:34 server.go:71: Using API v1
2016/11/28 21:24:34 debugger.go:65: launching process with args: [/Users/ahjesus/Git/work/debug]
could not launch process: could not get thread count

**Comment by aarzilli** [comment] 2016-11-28 18:24
Duplicate of #645.

**Closed by aarzilli** 2016-11-28 18:24 UTC
