### ISSUE TITLE
runtime.mach_semaphore_wait()

### ISSUE THREAD

**Issue by Wizermil** [derekparker/delve#483] opened 2016-04-03 18:13 UTC
1. What version of Delve are you using (`dlv version`)?
    Delve Debugger
    Version: 0.11.0-alpha
    Build: cfe0e52d040955efc34e7b34ef41313f03fe4864

2. What version of Go are you using? (`go version`)?
    go version go1.6 darwin/amd64

3. What operating system and processor architecture are you using?
    Max OS X 10.11.4
    Darwin Sarge.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

4. What did you do?
    I compiled this file: test.go
    ```go
    package main

    import (
    	"fmt"
    	"os"
    	"os/signal"
    )

    func main() {

    	c := make(chan os.Signal, 1)
    	signal.Notify(c, os.Interrupt)
    	done := make(chan bool, 1)

    	go func() {
    		select {
    		case <-done:
    			return
    		}
    	}()

    	select {
    	case <-c:
    		done <- true
    	}

    	fmt.Printf("hello, world\n")
    }
    ```
    and then run
    ```
    go build test.go
    dlv exec test
    ```
    Press Ctrl+C for (SIGINT)
    ```
    Type 'help' for list of commands.
    (dlv) c
    > runtime.mach_semaphore_wait() /usr/local/go/src/runtime/sys_darwin_amd64.s:411 (PC: 0x58ddb)
       406:	// func mach_semaphore_wait(sema uint32) int32
       407:	TEXT runtime·mach_semaphore_wait(SB),NOSPLIT,$0
       408:		MOVL	sema+0(FP), DI
       409:		MOVL	$(0x1000000+36), AX	// semaphore_wait_trap
       410:		SYSCALL
    => 411:		MOVL	AX, ret+8(FP)
       412:		RET
       413:
       414:	// func mach_semaphore_timedwait(sema, sec, nsec uint32) int32
       415:	TEXT runtime·mach_semaphore_timedwait(SB),NOSPLIT,$0
       416:		MOVL	sema+0(FP), DI
    (dlv) exit
    ```

5. What did you expect to see?
    I'm not sure that this go code is legit and I just wanted to see "hello world" when I send SIGINT to the process.
    My main goal is to properly stop a web server listening for request on a goroutine when it receives SIGINT but I thought this snippet was easier to read and reproduce the issue I have on a larger and more complex code base.
    In the terminal without delve it seems to be working but it doesn't mean there isn't a bug in this tiny snippet.
    Because I'm new to the language maybe someone can figure out if it's a delve issue or just bad code.

6. What did you see instead?
    There is this stacktrace letting me think that there is something wrong with my code.

**Comment by aarzilli** [comment] 2016-04-04 07:06
`^C` gets intercepted by delve causing it to stop the program. The code you are seeing is in fact legit, it's just part of runtime: use the commands `goroutines` and `stack` to find out what the program is doing.

If you want your program to receive SIGINT you should try sending SIGINT directly to the target process using `kill`, that will work on linux but I don't know if it will work on OS X.

**Comment by Wizermil** [comment] 2016-04-04 08:13
I tested this morning and it seems to be ok, SIGINT is handled as expected.

So it's a SIGINT issue with delve how can I help?

**Comment by aarzilli** [comment] 2016-04-04 09:16
Delve interrupting the process when ^C is pressed is not an issue, it's intended behavior.

**Comment by aarzilli** [comment] 2016-04-06 11:58
Closing this given that it's working as intended.

**Closed by aarzilli** 2016-04-06 11:58 UTC

**Comment by Wizermil** [comment] 2016-04-06 18:30
Hey @aarzilli,

There was something fishy related to delve and SIGINT it took me ages to pin point it but I finally found a way to reproduce it.

When running under delve your program can't receive SIGINT signal more than once. 

Here is my simple test.go file that can help you reproduce the issue
```go
package main

import (
	"fmt"
	"os"
	"os/signal"
)

func main() {
	fmt.Println("hello0")
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)
	<-c
	signal.Stop(c)

	fmt.Println("hello1")

	c2 := make(chan os.Signal, 1)
	signal.Notify(c2, os.Interrupt)
	<-c2
	signal.Stop(c2)

	fmt.Println("hello2")
}
```

after a simple
```
$ go build -race test.go
$ dlv exec test
Type 'help' for list of commands.
(dlv) c
hello0
```

then on another terminal

```
$ ps aux | grep test
wizermil        63314   0.0  0.0  2434840    788 s003  S+    8:19PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn test
wizermil        63244   0.0  0.1 573460536   5984 s004  SX    8:19PM   0:00.01 test
wizermil        63243   0.0  0.1 573434944  12356 s004  S+    8:19PM   0:00.07 dlv exec test
$ kill -2 63244
$ kill -2 63244
```

here is the result on the first terminal running dlv
```
$ dlv exec test
Type 'help' for list of commands.
(dlv) c
hello0
hello1
```

then with Ctrl+C you have the smaphore_wait() (that is by designed) but the main issue is that I can't quit the program without a kill -9 63243
```
> runtime.mach_semaphore_wait() /usr/local/go/src/runtime/sys_darwin_amd64.s:411 (PC: 0x5c38b)
   406:	// func mach_semaphore_wait(sema uint32) int32
   407:	TEXT runtime·mach_semaphore_wait(SB),NOSPLIT,$0
   408:		MOVL	sema+0(FP), DI
   409:		MOVL	$(0x1000000+36), AX	// semaphore_wait_trap
   410:		SYSCALL
=> 411:		MOVL	AX, ret+8(FP)
   412:		RET
   413:
   414:	// func mach_semaphore_timedwait(sema, sec, nsec uint32) int32
   415:	TEXT runtime·mach_semaphore_timedwait(SB),NOSPLIT,$0
   416:		MOVL	sema+0(FP), DI
(dlv) exit
```

**Comment by aarzilli** [comment] 2016-04-07 05:27
Ok that's a bug, thanks.
