### ISSUE TITLE
I'm developing Go software in a 32bit machine, which means I can't install Delve

### ISSUE THREAD

**Issue by shackra** [derekparker/delve#492] opened 2016-04-08 01:16 UTC
I'm experiencing the issue #456 

The reply there was that Delve doesn't compile in 32bits architecture. Well, I'm someone developing software on a IBM ThinkPad T60, and right now I have no money to buy a more modern laptop. If there nothing developers can do for me, what options do I have in terms of debugging tools?

```
GOARCH="386"
GOBIN="/home/jorge/go-workspace/bin"
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jorge/go-workspace"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_386"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by joegrasse** [comment] 2016-04-08 12:31
There is already issue #20 filed for this.

**Comment by derekparker** [comment] 2016-04-08 21:09
Closing as duplicate of #20. Please note this is something being worked on and not ignored.

**Closed by derekparker** 2016-04-08 21:09 UTC
