### ISSUE TITLE
could not launch process: malformed qfThreadInfo response

### ISSUE THREAD

**Issue by kurianCoding** [derekparker/delve#1319] opened 2018-08-22 17:21 UTC
I am trying to run delve on mavericks OS(10.9.5). 

1. What version of Delve are you using (`dlv version`)?
Version: 1.1.0
Build: 63c880780ff1e9ef7c765f19117770428badee32

2. What version of Go are you using? (`go version`)?
go version go1.10.3 darwin/amd64

3. What operating system and processor architecture are you using?

System: Mavericks (Mac OS 10.9.5),
Processor: i5
architecture: darwin

4. What did you do?
`dlv debug`

I tried

`export GOBIN=$GOPATH/bin dlv debug`

getting no difference.
5. What did you expect to see?
`[dlv]` prompt.

6. What did you see instead?
could not launch process: malformed qfThreadInfo response

**Comment by aarzilli** [comment] 2018-08-22 20:08
Duplicate of #1219

**Closed by aarzilli** 2018-08-22 20:08 UTC

**Comment by wupeaking** [comment] 2018-10-10 03:45
@aarzilli   Why do I only see you close the question, but don't answer how to solve it.

**Comment by chainhelen** [comment] 2018-10-10 05:51
@wupeaking 
Duplicate of #1219 .  

aarzilli say
> Closing, some old versions of debugserver are sending us a malformed version packet and there's nothing we can do about it.

**Comment by wupeaking** [comment] 2018-10-10 09:16
@chainhelen 

@kurianCoding say

`What version of Delve are you using (dlv version)?`
`Version: 1.1.0`
`Build: 63c8807`

I have not found a newer version.

**Comment by aarzilli** [comment] 2018-10-10 16:13
What @chainhelen said. If you are feeling particularly brave you could try deleting the block starting with `	if verbuf, err := p.conn.exec([]byte("$qGDBServerVersion"), "init"); err == nil {` 
in `pkg/proc/gdbserial/gdbserver.go`. But other things may be broken with that version of debugserver. In general this issue can not be fixed.
