### ISSUE TITLE
go build error ..\..\proc\disasm.go:9: undefined: ArchInst

### ISSUE THREAD

**Issue by CodyGuo** [derekparker/delve#693] opened 2017-01-04 01:33 UTC
go version:
go version go1.7 windows/386

go env:
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=G:\gopath
set GORACE=
set GOROOT=D:\go
set GOTOOLDIR=D:\go\pkg\tool\windows_386
set CC=gcc

go get -u -v github.com/derekparker/delve/cmd/dlv
error:
# github.com/derekparker/delve/proc
..\..\proc\disasm.go:9: undefined: ArchInst

**Comment by aarzilli** [comment] 2017-01-04 13:57
Duplicate of #656

**Closed by aarzilli** 2017-01-04 13:57 UTC
