### ISSUE TITLE
failed to compile delve when go get -u -v github.com/derekparker/delve/cmd/dlv

### ISSUE THREAD

**Issue by redhatlinux10** [derekparker/delve#559] opened 2016-05-30 02:28 UTC
1. What version of Delve are you using (`dlv version`)?

>the latest delve codes

2. What version of Go are you using? (`go version`)?

>go 1.6.2

3. What operating system and processor architecture are you using?
> windows 7 32bit
4. What did you do?

>go get -u -v github.com/derekparker/delve/cmd/dlv
github.com\derekparker\delve (download)
github.com/derekparker/delve/proc
\# github.com/derekparker/delve/proc
d:\GOPATH\EXT\src\github.com\derekparker\delve\proc\disasm.go:9: undefined: ArchInst

5. What did you expect to see?

>delve should be compiled without error

**Comment by aarzilli** [comment] 2016-05-30 04:00
Delve doesn't not have support for 32bit systems at the moment.

Duplicate of #20.

**Closed by aarzilli** 2016-05-30 04:00 UTC
