### ISSUE TITLE
Problem with Go 1.6.3 & Windows

### ISSUE THREAD

**Issue by loic59** [derekparker/delve#605] opened 2016-08-02 08:48 UTC
Os : Windows
Go version : 1.6.3
Dlv version : 0.11.0-alpha

Since version Go 1.6 I encounter this error with delve : 
`could not launch process: Could not determine version number: could not find symbol value for runtime.buildVersion`

Any ideas to fix the problems ?

**Comment by aarzilli** [comment] 2016-08-02 09:22
Duplicate of #477 (reopen if you aren't using cgo)

**Closed by aarzilli** 2016-08-02 09:22 UTC
