### ISSUE TITLE
Undefined ArchInst error when installing on w7 x86

### ISSUE THREAD

**Issue by lucas59356** [derekparker/delve#967] opened 2017-09-20 23:35 UTC
1. What version of Delve are you using (`dlv version`)?
Trying to use latest
2. What version of Go are you using? (`go version`)?
go version go1.9 windows/386
3. What operating system and processor architecture are you using?
Windows 7 x86 (AMD Athlon X2 250)
4. What did you do?
Try to install it
5. What did you expect to see?
Sucessful install
6. What did you see instead?
Compiling error

OUTPUT
```sh
$ go get github.com/derekparker/delve/cmd/dlv
# github.com/derekparker/delve/pkg/proc
C:\Users\User\go\src\github.com\derekparker\delve\pkg\proc\disasm.go:9:14: undefined: ArchInst
```

**Comment by aarzilli** [comment] 2017-09-21 07:58
Duplicate of #20

**Closed by aarzilli** 2017-09-21 07:58 UTC
