### ISSUE TITLE
Fail to compile for termux

### ISSUE THREAD

**Issue by chfanghr** [derekparker/delve#1453] opened 2019-01-04 02:02 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Master branch
2. What version of Go are you using? (`go version`)?
1.11.4
3. What operating system and processor architecture are you using?
Linux localhost 3.10.104 #4 SMP PREEMPT Fri Dec 14 15:02:40 CST 2018 aarch64 Android
4. What did you do?
```sh
u0_a34@localhost ~> go get -u -v github.com/derekparker/delve/cmd/dlv    
github.com/derekparker/delve (download)                                               
github.com/derekparker/delve/pkg/proc                                                
# github.com/derekparker/delve/pkg/proc                                               
go/src/github.com/derekparker/delve/pkg/proc/disasm.go:12:14: undefined: archInst
```
5. What did you expect to see?
6. What did you see instead?

**Comment by aarzilli** [comment] 2019-01-04 06:51
Duplicate of #118

**Closed by aarzilli** 2019-01-04 06:51 UTC
