### ISSUE TITLE
Error when trying to `go get`

### ISSUE THREAD

**Issue by jordyvandomselaar** [derekparker/delve#1344] opened 2018-09-16 10:11 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

2. What version of Go are you using? (`go version`)?

go version go1.9.2 darwin/amd64

3. What operating system and processor architecture are you using?

Mac os Mojave amd64

4. What did you do?

`➜  ~ go get -u github.com/derekparker/delve/cmd/dlv`

5. What did you expect to see?

An installed package

6. What did you see instead?

`/usr/local/go/pkg/tool/darwin_amd64/link: /usr/local/go/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)`

**Comment by aarzilli** [comment] 2018-09-17 14:35
Duplicate of https://github.com/golang/go/issues/25908

**Closed by aarzilli** 2018-09-17 14:35 UTC
