### ISSUE TITLE
Cannot see for loop variables 

### ISSUE THREAD

**Issue by deltaskelta** [derekparker/delve#1089] opened 2018-01-24 03:57 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.0.0-rc.2
Build: $Id: 5c7676404d10d52e16be57fea744a7312b831f0c $
```

2. What version of Go are you using? (`go version`)?

```
go version go1.9.3 darwin/amd64
```

3. What operating system and processor architecture are you using?

```
OSSierra 10.13.2
```

4. What did you do?

```
dlv test
```

then step through the program with `n` until inside a for loop. Calls `locals` and see for loop variables `for i, v := range foo {...}` missing from the listed variables

5. What did you expect to see?

for loop variables present and printable

6. What did you see instead?

for loop variables missing, only outer scope function variables were present. 

I also opened issue #1013 that was fixed by upgrading to `1.0.0-rc.1`, but the problem has reappeared with go `1.9.3` and `dlv 1.0.0-rc.2`.

I have not been using delve in the interim time so I am not sure when the issue came about again

**Comment by derekparker** [comment] 2018-01-24 18:20
Do you have a small example program that always reproduces this? I am not able to repro on a small test program, however I am running Linux and I see you're running OSX.

**Comment by deltaskelta** [comment] 2018-01-25 04:25
ok so I tried to reproduce on a simple program and I was unable (everything worked) so I will show you the real scenario I was in...

1. this repo/branch: https://github.com/deltaskelta/iota.lib.go/tree/TestBundle-test-hang
2. in the giota package (there is no main) I started `dlv` like this:
    ```
    $ dlv test -- -test.short
    $(dlv) break getValidHash
    $(dlv) continue
    $(dlv) n (x4)
    $(dlv) s
    ```

At this point you should be in a for loop like below and when I type `locals` this is what I see...

```
Warning: debugging optimized function
   113:		k := NewKerl()
   114:		hashedLen := BundleTrinaryOffset - AddressTrinaryOffset
   115:
   116:		buf := make(Trits, hashedLen*len(bs))
   117:		for i, b := range bs {
=> 118:			getTritsToHash(buf[i*hashedLen:], &b, i, len(bs))
   119:		}
   120:
   121:		for {
   122:			k.Absorb(buf)
   123:			hashTrits, _ := k.Squeeze(HashSize)
(dlv) locals
k = (*github.com/iotaledger/giota.Kerl)(0xc42003ed90)
buf = (unreadable unknown or unsupported kind: "invalid")
```

**Comment by derekparker** [comment] 2018-01-25 19:23
@deltaskelta thanks, I'll try and repro and see what the issue is.

**Comment by aarzilli** [comment] 2018-01-25 20:02
I can't investigate this properly now but I suspect that this is caused by the bug with dsymutil that we fixed in 1.10.

**Comment by derekparker** [comment] 2018-01-25 20:07
@aarzilli that could be. I may not be able to repro for a while as I don't actually have access to an OSX machine until I get back to the states. I suppose it may be time to set up a VM.

**Comment by deltaskelta** [comment] 2018-01-26 00:08
did anyone try my repro on another machine besides osx?

**Comment by dlsniper** [comment] 2018-01-26 00:11
@deltaskelta have you tried this with Go 1.10 RC1?

**Comment by aarzilli** [comment] 2018-01-26 14:21
Given that the test repository uses cgo extensively it's going to be affected by #964 / https://github.com/golang/go/issues/21945 for sure.

**Comment by aarzilli** [comment] 2018-05-09 08:12
1.10 should have fixed this problem, reopen if it hasn't. Thank you.

**Closed by aarzilli** 2018-05-09 08:12 UTC
Labels: kind/bug, kind/needs more info, os/OSX
