### ISSUE TITLE
Issiw with RPC: panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by pavel-odintsov** [derekparker/delve#622] opened 2016-08-25 16:10 UTC
Hello!

What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 0.11.0-alpha
Build: v0.11.0
```

What version of Go are you using? (`go version`)?

```
go version
go version go1.6.2 darwin/amd64
```

What operating system and processor architecture are you using?

Mac OS El Capitan

What did you do?

I'm trying to debug my application with Atom's go-debug plugin which uses Delve as backend. It uses RPC to Delve. Originally, this issue was sent to Go-Debug tracker: https://github.com/lloiser/go-debug/issues/51

I executed following steps:
- Start application under debugger
- Setup breakpoint
- Enter "continue"
- Hit code with breakpoint

What did you expect to see?

Working Delve RPC :)

What did you see instead?

```
Delve output: panic: runtime error: makeslice: len out of range
goroutine 10 [running]:
panic(0x4621860, 0xc821256e60)
 /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/derekparker/delve/proc.(*Thread).readMemory(0xc82174e370, 0xc82008e000, 0xfffffffffffffff0, 0x0, 0x0, 0x0, 0x0, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/threads_darwin.go:112 +0x9c
github.com/derekparker/delve/proc.cacheMemory(0x5b0b380, 0xc8216326f0, 0xc82008e000, 0xfffffffffffffff0, 0x0, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/mem.go:42 +0xf2
Delve output: github.com/derekparker/delve/proc.(*Variable).loadArrayValues(0xc821401420, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:938 +0xa6
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc821401420, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:744 +0x939
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc821401420)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:710 +0x2a
github.com/derekparker/delve/proc.(*EvalScope).extractVariableFromEntry(0xc821353810, 0xc821632450, 0x0, 0x0, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:499 +0x98
github.com/derekparker/delve/proc.(*EvalScope).variablesByTag(0xc821353810, 0x34, 0x0, 0x0, 0x0, 0x0, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:1484 +0x174
github.com/derekparker/delve/proc.(*EvalScope).LocalVariables(0xc821353810, 0x0, 0x0, 0x0, 0x0, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:530 +0x46
github.com/derekparker/delve/service/debugger.(*Debugger).convertStacktrace(0xc82005fcc0, 0xc821228000, 0x4, 0x15, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/debugger/debugger.go:521 +0x30e
github.com/derekparker/delve/service/debugger.(*Debugger).Stacktrace(0xc82005fcc0, 0x5b, 0x14, 0x44e6501, 0x0, 0x0, 0x0, 0x0, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/debugger/debugger.go:511 +0x188
github.com/derekparker/delve/service/rpc.(*RPCServer).StacktraceGoroutine(0xc8200dfa60, 0xc8203cb280, 0xc8203cb2e0, 0x0, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/rpc/server.go:120 +0x5d
reflect.Value.call(0x45cdca0, 0x46c5e28, 0x13, 0x46e54f8, 0x4, 0xc821353ed8, 0x3, 0x3, 0x0, 0x0, ...)
 /usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x45cdca0, 0x46c5e28, 0x13, 0xc821353ed8, 0x3, 0x3, 0x0, 0x0, 0x0)
 /usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:303 +0xb1
net/rpc.(*service).call(0xc82173c040, 0xc82173c000, 0xc82173e088, 0xc8217a6c80, 0xc8212bc0a0, 0x44eb600, 0xc8203cb280, 0x16, 0x44e6500, 0xc8203cb2e0, ...)
 /usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:383 +0x1c2
created by net/rpc.(*Server).ServeCodec
 /usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:477 +0x49d
delve closed with code 2
```

**Comment by aarzilli** [comment] 2016-08-26 12:50
Duplicate of #621

**Closed by aarzilli** 2016-08-26 12:50 UTC

**Comment by aarzilli** [comment] 2016-08-26 12:52
It looks like you are using an old version of delve, I fixed a similar bug a while ago and the fix already exists in master. Can you update to master and see if the issue still exists?
