### ISSUE TITLE
I modify the Makefile in ordering to debuging ,but cannot see the varalbe in delve.could you help me?

### ISSUE THREAD

**Issue by jiebanghan** [derekparker/delve#909] opened 2017-07-04 01:09 UTC
befor modifing The Makefile is below:
GOBIN = build/bin
GO ?= latest

geth:
build/env.sh go run build/ci.go install ./cmd/geth
@echo "Done building."
@echo "Run "$(GOBIN)/geth" to launch geth."

after modification below:

GOBIN = build/bin
GO ?= latest

geth:
build/env.sh go run -gcflags='-N -l' build/ci.go install ./cmd/geth
@echo "Done building."
@echo "Run "$(GOBIN)/geth" to launch geth."

i modified the Makefile above, but the error is the same. could not see the variable

1364: }
1365:
1366: // PrintBlock retrieves a block and returns its pretty printed form.
1367: func (api *PublicDebugAPI) PrintBlock(ctx context.Context, number uint64) (string, error) {
1368: block, _ := api.b.BlockByNumber(ctx, rpc.BlockNumber(number))
=>1369: if block == nil {
1370: return "", fmt.Errorf("block #%d not found", number)
1371: }
1372: return fmt.Sprintf("%s", block), nil
1373: }
1374:
(dlv) p block
Command failed: could not find symbol value for block
(dlv) p block
Command failed: could not find symbol value for block

**Comment by aarzilli** [comment] 2017-07-04 12:22
Duplicate of #906

**Closed by aarzilli** 2017-07-04 12:22 UTC
