### ISSUE TITLE
Windows dlv is not working

### ISSUE THREAD

**Issue by libbkmz** [derekparker/delve#556] opened 2016-05-29 18:00 UTC
I have hello world source code example, and I try to debug it, to be able to debug more complex applications.

main.go:

```
package main

import "fmt"

func main() {
    fmt.Println("test")
}
```

```
set
GOPATH=C:\Users\username\.go
GOROOT=C:\Go\
```
1. What version of Delve are you using (`dlv version`)?
   Delve Debugger
   Version: 0.11.0-alpha
   Build:
2. What version of Go are you using? (`go version`)?
   go version go1.6.2 windows/amd64
3. What operating system and processor architecture are you using?
   Windows 7 64bit, Intel XEON E5-1620
4. What did you do?
   `dlv debug`

```
Type 'help' for list of commands.
(dlv) list
Stopped at: 0x77c5cb71
=>no source available
(dlv) c
Stopped at: 0x7fefdcc940d
=>no source available
```
1. What did you expect to see?
   I want to run binary and execute it from debugger.
2. What did you see instead?
   no source availble

**Comment by derekparker** [comment] 2016-05-29 19:02
@libbkmz So you are unable to continue at all? Can you try just issuing the `continue` command as soon as the debugger starts up?

**Comment by libbkmz** [comment] 2016-05-29 19:04
@derekparker did you see, I've already tried "continue", but with "c" shortcut:
```
(dlv) c
Stopped at: 0x7fefdcc940d
=>no source available
```

**Comment by lukehoban** [comment] 2016-05-29 21:22
I just tested this on the latest Delve master sources, with otherwise similar configuration, and I don't see the same results you see.

Could there be anything else unusual in your environment?

```
c:\Users\Luke\dd\go\src\github.com\lukehoban\test>dlv version
Delve Debugger
Version: 0.11.0-alpha
Build:

c:\Users\Luke\dd\go\src\github.com\lukehoban\test>more main.go
package main

import "fmt"

func main() {
        fmt.Println("test")
}

c:\Users\Luke\dd\go\src\github.com\lukehoban\test>go version
go version go1.6.2 windows/amd64

c:\Users\Luke\dd\go\src\github.com\lukehoban\test>dlv debug
Type 'help' for list of commands.
(dlv) list
Stopped at: 0x7ff9267f1261
=>no source available
(dlv) c
test
Process 2656 has exited with status 0
(dlv) exit
Process 2656 has exited with status 0
```

**Comment by libbkmz** [comment] 2016-05-30 07:04
I'm not sure, but I think only environment variables could be different:
```
GOPATH=C:/Users/username/.go
GOROOT=C:\Go\
```

**Comment by alexbrainman** [comment] 2016-06-29 00:49
@libbkmz please build and executable out of your main.go program, like
```
go build -o a.exe main.go
```
and post a.exe somewhere so we could look at it.

Also what happens if you run a.exe on your computer? What does it outputs?

Thank you.

Alex

**Comment by libbkmz** [comment] 2016-06-29 07:02
@alexbrainman It prints "test", so as expected.

Here is a.exe binary: https://yadi.sk/d/ChUjj7msssJHG

**Comment by alexbrainman** [comment] 2016-07-01 06:46
I don't have problem debugging your executable:
```
U:\>dlv exec a.exe
Type 'help' for list of commands.
(dlv) c
test
Process 3528 has exited with status 0
(dlv) q
Process 3528 has exited with status 0

U:\>
```

I have used 323c0450 version of dlv.exe compiled with 29f0984 version of Go.

Can you try and do what I did above with same version of Go and Delve?

Maybe you have antivirus program that prevents you from debugging?

Are you admin on your computer? I am not sure, if that is important. I would expect dlv.exe to fail with "Access denied" error or similar if your credentials would be not up to scratch.

Alex

**Comment by aarzilli** [comment] 2017-02-09 15:20
Bugs similar to this were eventually traced back to corporate security (or League of Legends, same thing really) interfering with delve (or any other debugger). Since we can't reproduce it and we haven't had feedback in a while I'll close this.

**Closed by aarzilli** 2017-02-09 15:20 UTC
Labels: kind/bug, os/windows

**Comment by oadeojo** [comment] 2017-03-28 13:14
@aarzilli I am seeing this issue with CylancePROTECT AV. There has a reason why delve triggers the  AV to block it.

**Comment by aarzilli** [comment] 2017-03-28 16:56
@oadeojo probably because the same API that are used to debug programs are also often abused by malware to inject their code into other programs.

**Comment by bheimbaugh** [comment] 2018-05-30 16:20
I think I'm seeing the same error, and can reproduce it consistently on 64-bit Windows 7:
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\System32>echo %GOROOT%
C:\Go\

C:\Windows\System32>echo %GOPATH%
C:\Users\IBM_ADMIN\go

C:\Windows\System32>go version
go version go1.10 windows/amd64

C:\Windows\System32>dlv version
Delve Debugger
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533 $

C:\Windows\System32>cd %GOPATH%\src\hello

C:\Users\IBM_ADMIN\go\src\hello>dlv --log debug
2018/05/30 10:14:49 server.go:73: Using API v1
2018/05/30 10:14:49 debugger.go:101: launching process with args: [C:\Users\IBM_ADMIN\go\src\hello\d
ebug]
Type 'help' for list of commands.
(dlv) break main.main
2018/05/30 10:17:44 debugger.go:356: created breakpoint: &api.Breakpoint{ID:1, Name:"", Addr:0x4aa64
f, File:"C:/Users/IBM_ADMIN/go/src/hello/hello.go", Line:5, FunctionName:"main.main", Cond:"", Trace
point:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(nil)
, LoadLocals:(*api.LoadConfig)(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}
Breakpoint 1 set at 0x4aa64f for main.main() C:/Users/IBM_ADMIN/go/src/hello/hello.go:5
(dlv) continue
2018/05/30 10:18:22 debugger.go:513: continuing
     1: package main
     2:
     3: import "fmt"
     4:
=>   5: func main() {
     6:         fmt.Printf("Hello, world\n")
     7:         i := 101
     8:         fmt.Println(i)
     9: }
Command failed: Access is denied.
(dlv) q
```
At this point `dlv` is hung and will not accept further console input. [CTRL]-c will respond once:
[CTRL]-c => `received SIGINT, stopping process (will not forward signal)`
[CTRL]-c => _no response_
