### ISSUE TITLE
vips messes up next and step

### ISSUE THREAD

**Issue by gertcuykens** [derekparker/delve#1255] opened 2018-06-29 13:06 UTC
Delve Debugger OSX
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533
go version go1.10.2 darwin/amd64
```
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/davidbyttow/govips/pkg/vips"
)

var testChannel = make(chan os.Signal, 1)

func main() {
	x := 1
	fmt.Println("Hello 1", x)
	signal.Notify(testChannel, syscall.SIGTERM)
	signal.Notify(testChannel, os.Interrupt)
	fmt.Println("Hello 2", os.Getenv("ENVIRONMENT"))
	fmt.Println("Hello 2", x)
	vips.Startup(&vips.Config{
		ConcurrencyLevel: 1,
		MaxCacheFiles:    1,
		MaxCacheMem:      200 * 1024 * 1024,
		MaxCacheSize:     200,
		ReportLeaks:      false,
	})
	defer vips.Shutdown()
	var imgRef *vips.ImageRef
	imgRef, err := vips.NewImageFromFile("test.png")
	if err != nil {
		fmt.Printf("%v", err)
		return
	}
	defer imgRef.Close()
	fmt.Printf("%+v", imgRef.Height)
}
```
```
$ gert@mbp-2 ~/go/src/bitbucket.org/gertcuykens/lib/test (master)
$ dlv debug
Type 'help' for list of commands.
(dlv) b main.go:15
Breakpoint 1 set at 0x40d32d2 for main.main() ./main.go:15
(dlv) c
> main.main() ./main.go:15 (hits goroutine(1):1 total:1) (PC: 0x40d32d2)
    10: )
    11:
    12: var testChannel = make(chan os.Signal, 1)
    13:
    14: func main() {
=>  15:         x := 1
    16:         fmt.Println("Hello 1", x)
    17:         signal.Notify(testChannel, syscall.SIGTERM)
    18:         signal.Notify(testChannel, os.Interrupt)
    19:         fmt.Println("Hello 2", os.Getenv("ENVIRONMENT"))
    20:         fmt.Println("Hello 2", x)
(dlv) n
Hello 1 1
Hello 2 local
Hello 2 1
2018/06/29 14:58:02 Vips started with concurrency=1 cache_max_files=1 cache_max_mem=209715200 cache_max=200
2018/06/29 14:58:03 Registered image type loader type=tiff
2018/06/29 14:58:03 Registered image type loader type=webp
2018/06/29 14:58:03 Registered image type loader type=gif
2018/06/29 14:58:03 Registered image type loader type=jpeg
2018/06/29 14:58:03 Registered image type loader type=magick
2018/06/29 14:58:03 Registered image type loader type=pdf
2018/06/29 14:58:03 Registered image type loader type=png
2018/06/29 14:58:03 Registered image type loader type=svg
0x40d3c20> runtime.main() /usr/local/Cellar/go/1.10.2/libexec/src/runtime/proc.go:207 (PC: 0x402f630)
Warning: debugging optimized function
Values returned:

   202:
   203:         // Make racy client program work: if panicking on
   204:         // another goroutine at the same time as main returns,
   205:         // let the other goroutine finish printing the panic trace.
   206:         // Once it does, it will exit. See issues 3934 and 20018.
=> 207:         if atomic.Load(&runningPanicDefers) != 0 {
   208:                 // Running deferred functions should not take long.
   209:                 for c := 0; c < 1000; c++ {
   210:                         if atomic.Load(&runningPanicDefers) == 0 {
   211:                                 break
   212:                         }
(dlv) r
Process restarted with PID 92394
(dlv) c
> main.main() ./main.go:15 (hits goroutine(1):1 total:1) (PC: 0x40d32d2)
    10: )
    11:
    12: var testChannel = make(chan os.Signal, 1)
    13:
    14: func main() {
=>  15:         x := 1
    16:         fmt.Println("Hello 1", x)
    17:         signal.Notify(testChannel, syscall.SIGTERM)
    18:         signal.Notify(testChannel, os.Interrupt)
    19:         fmt.Println("Hello 2", os.Getenv("ENVIRONMENT"))
    20:         fmt.Println("Hello 2", x)
(dlv) s
Hello 1 1
Hello 2 local
Hello 2 1
2018/06/29 14:58:51 Vips started with concurrency=1 cache_max_files=1 cache_max_mem=209715200 cache_max=200
2018/06/29 14:58:51 Registered image type loader type=gif
2018/06/29 14:58:51 Registered image type loader type=jpeg
2018/06/29 14:58:51 Registered image type loader type=magick
2018/06/29 14:58:51 Registered image type loader type=pdf
2018/06/29 14:58:51 Registered image type loader type=png
2018/06/29 14:58:51 Registered image type loader type=svg
2018/06/29 14:58:51 Registered image type loader type=tiff
2018/06/29 14:58:51 Registered image type loader type=webp
0x40d3c20> runtime.main() /usr/local/Cellar/go/1.10.2/libexec/src/runtime/proc.go:207 (PC: 0x402f630)
Warning: debugging optimized function
Values returned:

   202:
   203:         // Make racy client program work: if panicking on
   204:         // another goroutine at the same time as main returns,
   205:         // let the other goroutine finish printing the panic trace.
   206:         // Once it does, it will exit. See issues 3934 and 20018.
=> 207:         if atomic.Load(&runningPanicDefers) != 0 {
   208:                 // Running deferred functions should not take long.
   209:                 for c := 0; c < 1000; c++ {
   210:                         if atomic.Load(&runningPanicDefers) == 0 {
   211:                                 break
   212:                         }
(dlv)
```
I expected next and step to go to the next line `16: fmt.Println("Hello 1", x)`

**Comment by aarzilli** [comment] 2018-07-02 09:44
Duplicate of #1254

**Closed by aarzilli** 2018-07-02 09:44 UTC
