### ISSUE TITLE
panic: runtime error: slice bounds out of range on win7 64bit os with dlv 0.11.0-alpha 

### ISSUE THREAD

**Issue by nkbai** [derekparker/delve#522] opened 2016-04-29 14:28 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.
1. What version of Delve are you using (`dlv version`)?
   Version: 0.11.0-alpha
   Build: 63a660820e7beef3b4870922e25897887392b188
2. What version of Go are you using? (`go version`)?
   1.5.1
3. What operating system and processor architecture are you using?
   win7 64 professional
4. What did you do?
   dlv.exe debug hello.go
5. What did you expect to see?
   run hello.exe and start to debug it

hello.go

``` go
package main

import "fmt"

func main(){
    fmt.Println("hello,world")
}

```
1. What did you see instead?
   panic: runtime error: slice bounds out of range

goroutine 35 [running]:
github.com/derekparker/delve/dwarf/frame.parseFDE(0xc082009840, 0xb9ddf0)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/dwarf/frame/parser.go:74 +0x406
github.com/derekparker/delve/dwarf/frame.Parse(0xc0822ec000, 0x10780, 0x10800, 0x2f61200, 0xdbb860, 0x0, 0x0, 0x0)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/dwarf/frame/parser.go:33 +0x1c8
github.com/derekparker/delve/proc.(_Process).parseDebugFrame(0xc08217a0e0, 0xc08217c0e0, 0xc082168210)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc_windows.go:174 +0x4df
created by github.com/derekparker/delve/proc.(_Process).LoadInformation
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc.go:154 +0x112

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc08216821c)
        c:/go/src/runtime/sema.go:43 +0x2d
sync.(_WaitGroup).Wait(0xc082168210)
        c:/go/src/sync/waitgroup.go:126 +0xbb
github.com/derekparker/delve/proc.(_Process).LoadInformation(0xc08217a0e0, 0xc08216e520, 0x15, 0x0, 0x0)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc.go:157 +0x18c
github.com/derekparker/delve/proc.initializeDebugProcess(0xc08217a0e0, 0xc08216e520, 0x15, 0x2f61100, 0x4, 0x0, 0x0)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc.go:707 +0x2a9
github.com/derekparker/delve/proc.Launch(0xc082168010, 0x1, 0x1, 0x0, 0x0, 0x0)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc_windows.go:103 +0xafc
github.com/derekparker/delve/service/debugger.New(0xc08216e160, 0xc08216e160, 0x0, 0x0)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/service/debugger/debugger.go:60 +0x384
github.com/derekparker/delve/service/rpc.(_ServerImpl).Run(0xc082176018, 0x0, 0x0)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/service/rpc/server.go:70 +0xbc
github.com/derekparker/delve/cmd/dlv/cmds.execute(0x0, 0xc082168010, 0x1, 0x1, 0xc0820ea048, 0x0)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:355 +0x2fc
github.com/derekparker/delve/cmd/dlv/cmds.debugCmd.func1(0xc0820fea00, 0xc0820e8660, 0x1, 0x1, 0x0)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:205 +0x676
github.com/derekparker/delve/cmd/dlv/cmds.debugCmd(0xc0820fea00, 0xc0820e8660, 0x1, 0x1)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:185 +0x46
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(_Command).execute(0xc0820fea00, 0xc0820e85f0, 0x1, 0x1, 0x0,
 0x0)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:569 +0x870
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(_Command).ExecuteC(0xc0820fe400, 0xc0820fea00, 0x0, 0x0)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:656 +0x572
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(_Command).Execute(0xc0820fe400, 0x0, 0x0)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:615 +0x34
main.main()
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/cmd/dlv/main.go:13 +0x51

goroutine 5 [syscall]:
os/signal.loop()
        c:/go/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
        c:/go/src/os/signal/signal_unix.go:28 +0x3e

goroutine 33 [chan receive, locked to thread]:
github.com/derekparker/delve/proc.(*Process).handlePtraceFuncs(0xc08217a0e0)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc.go:775 +0xd8
created by github.com/derekparker/delve/proc.New
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc.go:77 +0x1db

goroutine 36 [runnable, locked to thread]:
syscall.Syscall(0x77461800, 0x1, 0x1d4, 0x0, 0x0, 0x44ef50, 0xc0824a0000, 0x30d0000)
        c:/go/src/runtime/syscall_windows.go:128 +0x5c
syscall.GetFileType(0x1d4, 0x4bc14b, 0x0, 0x0)
        c:/go/src/syscall/zsyscall_windows.go:728 +0x6f
syscall.Seek(0x1d4, 0x0, 0x1, 0x150c00, 0x0, 0x0)
        c:/go/src/syscall/syscall_windows.go:346 +0x74
os.(_File).pread(0xc082176020, 0xc0824a0000, 0x150c00, 0x150c00, 0x400, 0x0, 0x0, 0x0)
        c:/go/src/os/file_windows.go:309 +0xed
os.(_File).ReadAt(0xc082176020, 0xc0824a0000, 0x150c00, 0x150c00, 0x400, 0x0, 0x0, 0x0)
        c:/go/src/os/file.go:117 +0xd3
io.(_SectionReader).ReadAt(0xc0822601b0, 0xc0824a0000, 0x150c00, 0x150c00, 0x400, 0x150c00, 0x0, 0x0)
        c:/go/src/io/io.go:493 +0x150
debug/pe.(_Section).Data(0xc082172690, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/debug/pe/file.go:75 +0xba
github.com/derekparker/delve/proc.loadPETable(0xc08217c0e0, 0xab0480, 0xe, 0xab0180, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc_windows.go:212 +0x3b0
github.com/derekparker/delve/proc.pcln(0xc08217c0e0, 0x401000, 0x0, 0x0, 0x0, 0xc0824560e0, 0x44ac8, 0x44b20, 0x0, 0x0)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc_windows.go:241 +0x2d7
github.com/derekparker/delve/proc.(_Process).obtainGoSymbols(0xc08217a0e0, 0xc08217c0e0, 0xc082168210)
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc_windows.go:254 +0x77
created by github.com/derekparker/delve/proc.(_Process).LoadInformation
        C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc.go:155 +0x148

**Comment by aarzilli** [comment] 2016-04-29 14:50
Probably a duplicate of #443. However this is more detailed.

**Comment by alexbrainman** [comment] 2016-05-01 00:14
@nkbai I followed your instructions,

```
c:\Users\Alex\dev\src\delve_issues\issue522>go version
go version go1.5.1 windows/amd64

c:\Users\Alex\dev\src\delve_issues\issue522>c:\Users\Alex\dev\src\github.com\derekparker\delve\cmd\dlv\dlv.exe version
Delve Debugger
Version: 0.11.0-alpha
Build:

c:\Users\Alex\dev\src\delve_issues\issue522>type hello.go
package main

import "fmt"

func main() {
        fmt.Println("hello,world")
}

c:\Users\Alex\dev\src\delve_issues\issue522>c:\Users\Alex\dev\src\github.com\derekparker\delve\cmd\dlv\dlv.exe debug hello.go
Type 'help' for list of commands.
(dlv) q

c:\Users\Alex\dev\src\delve_issues\issue522>
```

but I see no crash. What do you do different so it crashes?

Can you make delve crash by passing precompiled binary hello.exe to it? If you can, please, post copy of hello.exe somewhere - maybe I would be able to make delve crash this way.

Thank you.

Alex

**Comment by qiaozhjo** [comment] 2016-05-21 02:56
@nkbai   i face the same problem with you,and resolve it by set goenv GOARCH=amd64, check your go env and try this method.

**Comment by lukehoban** [comment] 2016-05-29 21:51
Per @qiaozhjo and similar to the report in #443 (https://github.com/derekparker/delve/issues/443#issuecomment-222384847), this is most likely a case of using a 32-bit Go installation on Windows, which is not supported.

**Comment by aarzilli** [comment] 2017-02-09 15:24
Similar bugs have been closed already and this issue hasn't seen activity in a while. Closing.

**Closed by aarzilli** 2017-02-09 15:24 UTC
Labels: area/dwarf, kind/bug, os/windows
