### ISSUE TITLE
Library: @rpath/libclntsh.dylib.12.1 not found when running under Delve

### ISSUE THREAD

**Issue by shayzu** [derekparker/delve#913] opened 2017-07-06 17:38 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

Shays-MacBook:oracle_db shayzukerman$ otool -L ./oracle_db
./oracle_db:
	@rpath/libclntsh.dylib.12.1 (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)

Shays-MacBook:oracle_db shayzukerman$ ./oracle_db
2 + 2 always equals: 4

Shays-MacBook:oracle_db shayzukerman$ dlv debug oracle_db
Type 'help' for list of commands.
(dlv) c
dyld: Library not loaded: @rpath/libclntsh.dylib.12.1
  Referenced from: /Users/shayzukerman/go/src/oracle_db/debug
  Reason: image not found
Process 867 has exited with status 0

1. What version of Delve are you using (`dlv version`)?

2. What version of Go are you using? (`go version`)? 1.0.0-rc.1
3. What operating system and processor architecture are you using?
Shays-MacBook:oracle_db shayzukerman$ uname -a
Darwin Shays-MacBook.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

4. What did you do?
Tested the program, which  was copied from  the page; [Accessing an Oracle DB in Go](https://gocodecloud.com/blog/2016/08/09/accessing-an-oracle-db-in-go).
This page instructs how to install and test the go-oci8 driver.
The program is using OCI8 driver  [go-oci8](https://github.com/mattn/go-oci8)
5. What did you expect to see?
The program's output, which is generated after connecting the database
6. What did you see instead?
dyld: Library not loaded: @rpath/libclntsh.dylib.12.1
  Referenced from: /Users/shayzukerman/go/src/oracle_db/debug
  Reason: image not found

When System Integrity Protection (SIP) is disabled - the issue does not happen and the debugged program is able to locate and load the library.
Is there any way to overcome the issue and set @rpath so the issue does not happen?

Thanks

Shay

**Comment by aarzilli** [comment] 2017-07-07 09:08
Duplicate of #877?

**Comment by shayzu** [comment] 2017-07-07 15:50
Hi,

That's looks exactly as the issue I have reported - the process, which Delve is creating is missing some of the environment's parameters or it blocks the access to the search paths pf the Shared libraries.
Anyway, as I have already found - disabling "SIP" bypasses the issue  - but **_I HATE THAT!_**
Thanks!

Shay

**Closed** 2017-07-26 21:16 UTC
