### ISSUE TITLE
When I install delve,then tell me undefined

### ISSUE THREAD

**Issue by yyf1986** [derekparker/delve#859] opened 2017-06-02 06:24 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
git clone  https://github.com/derekparker/delve.git 
go install github.com/derekparker/delve/cmd/dlv
2. What version of Go are you using? (`go version`)?
go version go1.7.3 windows/386
3.ERROR
# github.com/derekparker/delve/pkg/proc
D:\WorkSpace\Go\src\github.com\derekparker\delve\pkg\proc\disasm.go:9: undefined
: ArchInst

**Comment by aarzilli** [comment] 2017-06-03 14:37
Duplicate of #656

**Closed by aarzilli** 2017-06-03 14:37 UTC

**Comment by yyf1986** [comment] 2017-06-07 02:07
my GOARCH=386，when I set GOARCH=amd64，I run ‘go get github.com/derekparker/delve/cmd/dlv’ is ok，but when I debug my code 
2017/06/07 10:01:24 server.go:73: Using API v1
2017/06/07 10:01:24 debugger.go:97: launching process with args: [d:\WorkSpace\Go\src\gogo\debug]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xe8 pc=0x640954]
goroutine 1 [running]:
panic(0x943ec0, 0xc04200c080)
	C:/go/src/runtime/panic.go:500 +0x1af
github.com/derekparker/delve/vendor/golang.org/x/debug/dwarf.(*Reader).Seek(0xc04231e000, 0xc000000000)
	D:/WorkSpace/Go/src/github.com/derekparker/delve/vendor/golang.org/x/debug/dwarf/entry.go:308 +0x364

**Comment by aarzilli** [comment] 2017-06-07 05:26
If the output of `go version` is still `go version go1.7.3 windows/386` you will need to compile everything you intend to debug with delve with `GOARCH=amd64`

**Comment by hellojukay** [comment] 2017-08-26 14:38
if solve this probleam by run  set GOARCH=amd64 in cmd console before building dlv,then you  can see a folder id your $GOPATH/bin. and dlv is in this folder,then ,move it out.
