### ISSUE TITLE
could not launch process: could not get .debug_frame section: could not find .debug_frame section

### ISSUE THREAD

**Issue by zolotov** [derekparker/delve#1269] opened 2018-07-18 14:32 UTC
Delve Debugger
Version: 1.0.0
Build: 2925c0310a76b54c725e380776e251ce16417fe1

From https://youtrack.jetbrains.com/issue/GO-5915

```
go get github.com/hyperledger/fabric-ca
go build -o /tmp/___go_build_github_com_hyperledger_fabric_ca_cmd_fabric_ca_server -gcflags "all=-N -l" github.com/hyperledger/fabric-ca/cmd/fabric-ca-server
dlv --api-version=2 --backend=default exec /tmp/___go_build_github_com_hyperledger_fabric_ca_cmd_fabric_ca_server --
```

it produces 

```
could not launch process: could not get .debug_frame section: could not find .debug_frame section

<fabric usage help here>
```

And terminated.

**Comment by aarzilli** [comment] 2018-07-18 14:40
Probably just a duplicate of https://github.com/golang/go/issues/23733

**Closed** 2018-10-18 22:16 UTC
