### ISSUE TITLE
Get full variable value instead of "+XXX more" while value is long

### ISSUE THREAD

**Issue by Yang09701194** [derekparker/delve#1190] opened 2018-04-19 06:30 UTC
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533 $
2. What version of Go are you using? (`go version`)?  
go version go1.9.1 windows/amd64
3. What operating system and processor architecture are you using?
Win7 x64
4. What did you do?  

Not sure if this issue should be posted here,

I'm using debugger to see and copy variable value in vscode, I hope I can get full value, but now if the value is long, the value will be abridged and show "+XXX more", as in the issue **Microsoft/vscode/issues/46288** , and vscode team say the issue should post to the debugger repository, so I come here.

![image](https://user-images.githubusercontent.com/23180780/38974706-b3628cac-43dd-11e8-9591-0d5a01679794.png)

5. What did you expect to see, what did you see instead??
In the variable region of vscode, I need to copy the full variable value instead of "+XXX more"

**Comment by aarzilli** [comment] 2018-04-19 08:34
This shouldn't be implemented because for corrupted or uninitialized variables the length could be very large. The front end should ask for a suitably large maximum length.

**Comment by Yang09701194** [comment] 2018-04-19 08:52
I'm a beginner level programmer and my ability may be insufficient to join this discussion, so I think I just post the issue and not going to give opinion  :relieved: .

**Comment by aarzilli** [comment] 2018-04-19 09:33
Duplicate of https://github.com/Microsoft/vscode-go/issues/868

**Closed by aarzilli** 2018-04-19 09:33 UTC
