### ISSUE TITLE
step should enter main first line

### ISSUE THREAD

**Issue by gertcuykens** [derekparker/delve#1252] opened 2018-06-29 09:13 UTC
Delve Debugger OSX
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533
go version go1.10.2 darwin/amd64
```
package main

import (
	"fmt"
	"os"
)

func main() {
	x := 1
	fmt.Println("Hello 1", x)
	fmt.Println("Hello 2", os.Getenv("ENVIRONMENT"))
	fmt.Println("Hello 2", x)
}
```
When doing step immediately as frist command main doesn't get stepped into
```
$ dlv debug
Type 'help' for list of commands.
(dlv) s
Hello 1 1
Hello 2 local
Hello 2 1
Process has exited with status 0
(dlv)
```
It should step into main instead

**Comment by dlsniper** [comment] 2018-06-29 09:39
I think it should step into the first execution that runs, rather than straight to ` main() `.

**Comment by aarzilli** [comment] 2018-07-02 09:36
Duplicate of #374

**Closed by aarzilli** 2018-07-02 09:36 UTC
