### ISSUE TITLE
macOS with VSCode delve throws Failed to continue

### ISSUE THREAD

**Issue by ArkadyB** [derekparker/delve#977] opened 2017-10-02 17:24 UTC
1. What version of Delve are you using (`dlv version`)? 1.0.0-rc.1
2. What version of Go are you using? (`go version`)? 1.9
3. What operating system and processor architecture are you using? macOS Sierra 10.12.6
4. What did you do? Downloaded latest master source codes and run make install. Checked dlv to work properly by going into app folder and run "dlv debug". Exited debugging process. Then i tried to open VSCode and launch the app.
5. What did you expect to see? Expected app to run
6. What did you see instead? Go-kit logged a message and then debugger failed.

> API server listening at: 127.0.0.1:8080
> 2017/10/02 19:15:21 debugger.go:499: continuing
> Failed to continue.

Any idea? Is it me doing something wrong?

**Comment by aarzilli** [comment] 2017-10-02 17:47
Probably a duplicate of #852 but:

> What did you see instead? Go-kit logged a message and then debugger failed.

it would help to know exactly what the message was.

**Comment by ArkadyB** [comment] 2017-10-02 20:21
here you go complete output:

> 2017/10/02 22:19:26 server.go:73: Using API v1
> 2017/10/02 22:19:26 debugger.go:97: launching process with args: [/Users/macos/go/src/bitbucket.org/arkadyb/demo_microservice/cmd/debug]
> API server listening at: 127.0.0.1:8080
> 2017/10/02 22:19:26 debugger.go:499: continuing
> Failed to continue.

**Comment by aarzilli** [comment] 2017-10-02 20:26
:This doesn't mention go-kit anywhere.

**Comment by ArkadyB** [comment] 2017-10-03 08:24
Feel free to check it: `go get bitbucket.org/arkadyb/demo_microservice`

Debugger works for me for this repo on Ubuntu with te following configuration:
1. dlv version = 0.12.1
2. go version = 1.8
3. OS = Ubuntu 16.04 LTS

**Comment by aarzilli** [comment] 2017-10-03 08:30
Duplicate of #852, if you have the latest version (built from master) of delve then you should be getting an error describing why the continue failed, if you aren't this is a bug with VSCode.

**Closed by aarzilli** 2017-10-03 08:30 UTC

**Comment by christianklotz** [comment] 2017-10-06 10:07
I experience the same behaviour on macOS 10.13 High Sierra even with the most basic application. The key issue seems to be related to setting breakpoints.

```go
package main

import "fmt"

func main() {
	fmt.Println("Hello world") // set breakpoint here
}
```
## Console output 
**Operating system:** macOS 10.13 (17A365)
**go:** go1.9.1 darwin/amd64
**Delve:** v0.12.1 (Build: bb07fc36b9df2b9baec074ee8a48b1941f049f55)
**Visual Studio Code**: Version 1.17.0 (1.17.0)

---

### Without breakpoint
Completes the application and outputs the print statement.
```shell
API server listening at: 127.0.0.1:49026
Hello world
```

### With breakpoint
With the breakpoint set the debugger seems to pause since it still showing the debugging controls and doesn't complete the application.

```shell
API server listening at: 127.0.0.1:44976
Failed to continue.
```

**Comment by aarzilli** [comment] 2017-10-06 10:13
@christianklotz clearly not the same problem, also old version of delve that doesn't support 1.9

**Comment by christianklotz** [comment] 2017-10-06 10:45
@aarzilli thank you for pointing me at the version 🙏. There were two versions of Delve installed on my machine, one through `brew` (v1.0.0-rc1) the other one directly into the `$GOPATH`.

**Comment by damongant** [comment] 2018-05-15 13:54
running a freshly compiled copy from master on high sierra, segfaults will do this without showing the actual stack, which is annoying because there's no easy way to not use dlv in your configuration
