### ISSUE TITLE
x86 (32bit os support please)

### ISSUE THREAD

**Issue by MiyamuraMiyako** [derekparker/delve#1061] opened 2017-12-30 02:15 UTC
current delve can not use on 32bit os.

**Comment by aarzilli** [comment] 2017-12-30 08:22
Duplicate of #20.

**Closed by aarzilli** 2017-12-30 08:22 UTC

**Comment by MiyamuraMiyako** [comment] 2017-12-30 08:33
@aarzilli Sorry, but I can't find any solution for this on #20

**Comment by aarzilli** [comment] 2017-12-30 08:35
There isn't one, somebody has to do the work.
